SpineEventEngine/base

- .idea/inspectionProfiles/Project_Default.xml
- gradle-plugins/model-compiler/src/main/java/io/spine/gradle/compiler/Extension.java
- gradle-plugins/model-compiler/src/main/java/io/spine/gradle/compiler/lookup/enrichments/EnrichmentLookupPlugin.java
- gradle-plugins/model-compiler/src/main/java/io/spine/gradle/compiler/lookup/proto/ProtoToJavaMapperPlugin.java
- gradle-plugins/model-compiler/src/main/java/io/spine/gradle/compiler/validate/RepeatedFieldMethodConstructor.java
Reduce the issue level to "typo" in IDEA settings.
> Method naming convention change.

- base/src/main/java/io/spine/reflect/Types.java
- base/src/test/java/io/spine/base/TypesShould.java
- ext.gradle
Move 'Types' from 'base' to 'reflect' package.
> Move 'Types' from 'base' to 'reflect' package.

- .travis.yml
- scripts/publish-artifacts.sh
This PR resolves the [issue](https://github.com/SpineEventEngine/core-java/issues/558).
> Fail the CI build if artifact publishing fails

- ext.gradle
This PR releases Spine `base` version `0.10.0`.
> Release v0.10.0

- ext.gradle
This PR contains changes to docs in `ext.gradle`.
Now, we have an explanation of how to increment the version.
> Describe version changing

- ext.gradle
This PR updates the version of Spine.
> Update the version of Spine

- base/src/main/java/io/spine/code/proto/Type.java
- base/src/main/java/io/spine/code/proto/TypeSet.java
- base/src/main/java/io/spine/type/KnownTypes.java
- base/src/main/java/io/spine/type/TypeUrl.java
- base/src/test/java/io/spine/type/KnownTypesTest.java
- ext.gradle
- testlib/src/test/java/io/spine/testing/VerifyShould.java
This PR introduces additional improvements to working with type-related classes. In particular:
* `KnownTypes` transformed into `enum`.
* `Type`, `TypeSet` were made `@Immutable`
> Improvements to type-related classes

- base/src/main/java/io/spine/annotation/Internal.java
- base/src/main/java/io/spine/base/ThrowableMessage.java
- ext.gradle
This PR makes `@Internal` annotation `@Inherited`.
> Inherit `@Internal`

- base/src/main/java/io/spine/annotation/Internal.java
- ext.gradle
This PR removes inheritance for `@Internal` annotation.
> Revert internal inheritance

- .idea/inspectionProfiles/Project_Default.xml
- base/src/main/java/io/spine/logging/Logging.java
- base/src/test/java/io/spine/logging/LoggingMethodTest.java
- ext.gradle
- tools/smoke-tests/validation-rules/src/test/java/io.spine/validate/MessageFieldValidatorShould.java
This PR adds missing logging shortcut methods for the `INFO` level.
> Info level

- ext.gradle
- gradle/wrapper/gradle-wrapper.properties
- tools/javadoc-prettifier/src/test/java/io/spine/tools/protodoc/JavadocFormatterShould.java
- tools/javadoc-prettifier/src/test/java/io/spine/tools/protodoc/ProtoJavadocPluginShould.java
- tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/ErrorProneChecksExtensionShould.java
- tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/ExtensionShould.java
- tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/ProtoAnnotatorPluginShould.java
- tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/RejectionGenPluginShould.java
- tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/ValidatingBuilderGenPluginShould.java
- tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/ValidationRulesLookupPluginShould.java
- tools/plugin-testlib/src/main/java/io/spine/tools/gradle/GradleProject.java
- tools/plugin-testlib/src/test/java/io/spine/tools/gradle/GradleProjectTest.java
- tools/smoke-tests/build.gradle
Also:
* Bump Gradle -> `4.10.2`
* Fix dependency on Spine Testlib
> Use non-final fields for `@Rule`

- version.gradle
With this PR we publish the first pre-release version of base.
> Release 1.0.0-pre1

- .idea/inspectionProfiles/Project_Default.xml
- base/src/main/java/io/spine/code/generate/Indent.java
- base/src/main/java/io/spine/code/generate/IndentLevel.java
- base/src/main/proto/spine/options.proto
- tools/model-compiler/src/main/java/io/spine/tools/compiler/SourceProtoBelongsToModule.java
- tools/model-compiler/src/main/java/io/spine/tools/compiler/enrichment/EnrichmentMap.java
- tools/model-compiler/src/main/java/io/spine/tools/compiler/rejection/RejectionBuilderWriter.java
- tools/model-compiler/src/main/java/io/spine/tools/compiler/validation/VBuilderGenerator.java
- tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/RejectionGenPlugin.java
- tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/ValidatingBuilderGenPlugin.java
- tools/plugin-base/src/main/java/io/spine/tools/gradle/CodeGenerationAction.java
- tools/plugin-base/src/main/java/io/spine/tools/gradle/SpinePlugin.java
This PR:
* Fixes the issue of duplicated rejection generations (#300)
* Removes outdated proto doc for the `by` option
> Fix repeated rejection generation

- testlib/src/main/java/io/spine/testing/ReflectiveBuilder.java
- testlib/src/test/java/io/spine/testing/ReflectiveBuilderTest.java
This PR introduces two method name changes in `ReflectiveBuilder` class.
> Improve method names

- base/src/main/java/io/spine/validate/diags/ViolationText.java
This PR adds backtick quotes for validation error output.
> Backtick code text in validation error message

- license-report.md
- testlib/src/main/java/io/spine/testing/Tests.java
- testlib/src/test/java/io/spine/testing/TestsTest.java
This PR adds a testing utility for repeating an action a number of times.
It is test-only utility to avoid such constructs in a production code because cycles should have domain-specific semantics.
> Add repeating testing utility

- base/src/main/java/io/spine/annotation/Beta.java
- base/src/main/java/io/spine/annotation/Experimental.java
- base/src/main/java/io/spine/annotation/GeneratedMixin.java
- base/src/main/java/io/spine/annotation/Internal.java
- base/src/main/java/io/spine/annotation/SPI.java
- base/src/main/java/io/spine/base/Environment.java
- base/src/main/java/io/spine/base/Identifier.java
- base/src/main/java/io/spine/base/ThrowableMessage.java
- base/src/main/java/io/spine/base/Time.java
Minor changes to API comments in annotation and base packages API comments
> API comments of annotation and base packages revised and edited

- .gitignore
- base/src/main/java/io/spine/code/proto/FieldDeclaration.java
This PR makes the field declaration consider a repeated or a map field being _not_ an ID field when it comes first in the state message.
> ID field cannot be a collection

- appveyor.yml
With this PR I have added support for AppVeyor Windows builds to the repository.
> Add AppVeyor Windows builds

- appveyor.yml
- license-report.md
- pom.xml
In this PR I have added `after_build` script to the AppVeyor CI configuration that discovers and uploads JUnit test result to the AppVeyor test result REST [endpoint](https://www.appveyor.com/docs/running-tests/#uploading-xml-test-results).
> Record tests in AppVeyor

- base/src/main/java/io/spine/security/InvocationGuard.java
- license-report.md
This PR fixes error message format in `InvocationGuard`.
> Fix error message format

- .idea/inspectionProfiles/Project_Default.xml
- base/src/main/java/io/spine/validate/FieldAwareMessage.java
- base/src/main/java/io/spine/validate/MessageValue.java
- build.gradle
This PR enforces `UTF-8` for `JavaCompile` tasks.
> Enforce compilation encoding

- license-report.md
- pom.xml
- version.gradle
This changeset releases the `1.0.3` version of `base` modules.
> Release `1.0.3`

- base/src/main/java/io/spine/base/Field.java
- base/src/main/java/io/spine/base/FieldPaths.java
- base/src/main/java/io/spine/code/proto/FieldName.java
- base/src/main/java/io/spine/validate/diags/ViolationText.java
- base/src/test/java/io/spine/base/FieldPathsTest.java
- base/src/test/java/io/spine/base/FieldTest.java
- base/src/test/java/io/spine/validate/ValidateTest.java
- base/src/test/java/io/spine/validate/diags/ViolationTextTest.java
- base/src/test/proto/spine/test/protobuf/field_paths_test.proto
- license-report.md
- pom.xml
- version.gradle
This PR introduces the `Field` class which aims to encapsulate working with field paths and thus replace utilities from `FieldPaths` class.
> Path of fields

- base/build.gradle
- license-report.md
- pom.xml
- tools/mute-logging/build.gradle
- tools/tool-base/build.gradle
This PR removes dependency on Slf4J (which is not used already).
> Remove Slf4j dependency

- .github/workflows/win.yml
- .idea/dictionaries/common.xml
This PR introduces GitHub Actions into `base`.
For now, we use Actions to run tests on Windows for PRs.
> GitHub Actions

- license-report.md
- pom.xml
- version.gradle
This PR releases the version `1.1.0` of the library which is to be followed by releases of all the other parts of the framework.
> Release 1.1.0

- .idea/inspectionProfiles/Project_Default.xml
- base/src/main/java/io/spine/base/Field.java
- base/src/test/java/io/spine/base/FieldTest.java
- license-report.md
- pom.xml
- version.gradle
This PR adds the ability to obtain a field reference by its number as declared in a proto type.
> Field by number

- base/src/main/java/io/spine/io/Resource.java
- base/src/main/java/io/spine/security/CallerProvider.java
- base/src/main/java/io/spine/security/InvocationGuard.java
- base/src/test/java/io/spine/security/InvocationGuardTest.java
- license-report.md
- pom.xml
- tools/proto-dart-plugin/src/main/java/io/spine/generate/dart/ProtoDartPlugin.java
- version.gradle
This PR allows the `Resource` instance to be created with a custom `ClassLoader`. By default, `Resource.class.getClassLoader()` will be used.
> Custom resource class loader

- license-report.md
- tools/dart-code-gen/build.gradle
- tools/dart-code-gen/lib/src/bytes_validator_factory.dart
- tools/dart-code-gen/lib/src/enum_validator_factory.dart
- tools/dart-code-gen/lib/src/field_validator_factory.dart
- tools/dart-code-gen/lib/src/message_validator_factory.dart
- tools/dart-code-gen/lib/src/number_validator_factory.dart
- tools/dart-code-gen/lib/src/string_validator_factory.dart
- tools/smoke-tests/dart-codegen-tests/src/main/proto/spine/test/tools/dart/validation.proto
- tools/smoke-tests/dart-codegen-tests/test/validation_test.dart
In this PR we add support for generating validation Dart code for `repeated` and `map` fields.
Those fields can be checked according to the `(required)` and `(distinct)` options.
> Repeated fields in Dart generated validation

- license-report.md
- tools/proto-dart-plugin/src/main/java/io/spine/generate/dart/ProtoDartPlugin.java
- tools/proto-dart-plugin/src/test/java/io/spine/generate/dart/ProtoDartPluginTest.java
This PR adds some unit tests for the `ProtoDartPlugin` and fixes an apparent issue in the plugin.
> Proto Dart plugin tests

- gradle/wrapper/gradle-wrapper.properties
- license-report.md
- pom.xml
- tools/model-compiler/build.gradle
- tools/model-compiler/src/main/java/io/spine/tools/compiler/annotation/Annotator.java
- tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/ProtoAnnotatorPluginTest.java
- tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/RejectionGenPluginTest.java
- tools/smoke-tests/gradle/wrapper/gradle-wrapper.properties
- version.gradle
In this PR we update third-party dependency versions. This includes the new Gradle 6.0.
The version of the lib is updated to `1.2.1`.
> Update dependency versions

- base/src/main/java/io/spine/protobuf/AnyPacker.java
- base/src/main/java/io/spine/validate/ComparableNumber.java
- base/src/test/java/io/spine/net/EmailAddressesTest.java
- base/src/test/java/io/spine/net/InternetDomainsTest.java
- license-report.md
- pom.xml
- tools/model-compiler/src/main/java/io/spine/tools/compiler/check/SeverityConfigurer.java
- tools/proto-js-plugin/src/test/java/io/spine/js/generate/resolve/JsFileTest.java
- version.gradle
This PR moves the `base` library and tools to the version `1.4`.
The main changes in `1.4` are:
- generated validation code;
- updated third-party dependencies.
> Release 1.4

- base/src/main/java/io/spine/code/proto/FileSet.java
- base/src/main/java/io/spine/code/proto/RejectionsFile.java
- base/src/main/java/io/spine/code/proto/SourceFile.java
- base/src/test/java/io/spine/code/proto/FileSetTest.java
- base/src/test/java/io/spine/code/proto/RejectionsFileTest.java
- base/src/test/proto/spine/test/code/proto/fake_rejections.proto
- base/src/test/proto/spine/test/code/proto/more_fake_rejections.proto
- license-report.md
- pom.xml
- version.gradle
This PR improves the errors a user may see when building a project with Model Compiler.
> More helpful errors

- .idea/misc.xml
- base/src/main/proto/spine/ui/language.proto
- license-report.md
- pom.xml
- version.gradle
This PR adds members of the `Language` type (thus addressing #2).
> Define `Language` members

- base/src/main/java/io/spine/validate/Validate.java
- base/src/test/java/io/spine/validate/ValidateTest.java
- license-report.md
- pom.xml
- version.gradle
Currently, we only provide a method for throwing a `ValidationException` if the `(set_once)` constraint is violated. However, it can also be helpful to be able to obtain violations without an exception. For that, we introduce the new `Validate.validateChange(..)` method.
> `ConstraintViolation`s for `(set_once)`

- base/src/main/java/io/spine/validate/ComparableNumber.java
- base/src/main/java/io/spine/validate/option/FieldValidatingOption.java
- base/src/main/java/io/spine/validate/option/RangedConstraint.java
- base/src/test/java/io/spine/validate/ComparableNumberTest.java
- base/src/test/java/io/spine/validate/NumberRangeTest.java
- base/src/test/proto/spine/test/validate/messages.proto
- license-report.md
- pom.xml
- tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/ColumnGenAction.java
- tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/ColumnGenPlugin.java
- version.gradle.kts
Starting from now, we will check that `(min)`, `(max)`, and `(range)` constraints on whole numbers (`int32`, etc.) are themselves whole numbers.
Also, some leftover debug output is trimmed.
> Verify number validation options

- license-report.md
- pom.xml
- tools/plugin-base/src/main/java/io/spine/tools/gradle/GradlePlugin.java
- tools/plugin-base/src/main/java/io/spine/tools/gradle/project/PlugableProject.java
- tools/plugin-base/src/main/java/io/spine/tools/gradle/project/PluginTarget.java
- tools/plugin-base/src/test/java/io/spine/tools/gradle/project/PlugableProjectTest.java
- tools/plugin-testlib/src/main/java/io/spine/tools/gradle/testing/MemoizingPluginRegistry.java
- version.gradle.kts
This PR adds API for triggering an action when a Gradle plugin is applied to a project.
This is a wrapper API for Gradle's `PluginContainer.withType(..)` own API, but made tidier.
> Add plugin trigger API

- .idea/misc.xml
- license-report.md
- pom.xml
- testlib/src/main/java/io/spine/testing/ClassTest.java
- testlib/src/main/java/io/spine/testing/SingletonTest.java
- testlib/src/main/java/io/spine/testing/Tests.java
- testlib/src/main/java/io/spine/testing/UtilityClassTest.java
- testlib/src/test/java/io/spine/testing/SingletonTestTest.java
- testlib/src/test/java/io/spine/testing/given/SingletonTestEnv.java
- tools/errorprone-checks/src/main/java/io/spine/tools/check/vbuild/UseVBuild.java
- version.gradle.kts
This PR improves utilities for testing classes:
* Common abstract base `ClassTest` was created.
* `UtilityClassTest` is derived from `ClassTest`.
* `UtilityClassTest.getUtilityClass()` deprecated in favor of `ClassTest.subject()`.
* `SingletonClassTest` was introduced (#186).
> Class tests

- base/src/main/kotlin/io/spine/base/ThrowableExtensions.kt
- base/src/test/kotlin/io/spine/base/ThrowableExtensionsKtTest.kt
- buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
- license-report.md
- pom.xml
- version.gradle.kts
This PR adds `causedByRejection()` function to a `Throwable`.
> `Throwable` extension `causedByRejection()`

- .github/workflows/publish.yml
- license-report.md
- pom.xml
- version.gradle.kts
This PR fixes publishing by updating to latest `config`.
> Fix publishing

- base/build.gradle.kts
- base/src/main/java/io/spine/reflect/J2Kt.java
- base/src/test/java/io/spine/reflect/J2KtTest.java
- base/src/test/kotlin/io/spine/reflect/given/MethodHolder.kt
- license-report.md
- pom.xml
- version.gradle.kts
In this PR we add a utility that allows integration of Java and Kotlin reflection API.
> Java-to-Kotlin reflection

- base/src/main/kotlin/io/spine/protobuf/AnyExtensions.kt
- base/src/test/kotlin/io/spine/protobuf/AnyExtensionsTest.kt
- license-report.md
- pom.xml
- version.gradle.kts
In this PR we introduce a few Kotlin extension functions related to `Any` packing and unpacking:
- `Any.unpack<T>()` unpacks the `Any` into the given type using `AnyPacker`;
- `Any.unpackGuessingType()` infers the message type from the type URL and unpacks the `Any` using `AnyPacker`;
- `Message.pack()` packs the message into an `Any` using `AnyPacker`.
> Any Kotlin extensions

- license-report.md
- pom.xml
- version.gradle.kts
This is an attempt to publish the artifacts.
The [previous](https://github.com/SpineEventEngine/base/runs/3123766397) CI build failed due to a mysterious conflict. As the result, publishing happened partially and only on GitHub Packages, not on CloudRepo.
> Poke publishing

- license-report.md
- pom.xml
- version.gradle.kts
This changeset sets the version to `1.8.0` and updates the corresponding license report files.
> Release 1.8.0

- .idea/misc.xml
- base/src/main/java/io/spine/code/proto/FileDescriptors.java
- base/src/main/java/io/spine/code/proto/FileSet.java
- base/src/main/java/io/spine/type/KnownTypes.java
- base/src/main/java/io/spine/util/Predicates2.java
- base/src/test/java/io/spine/type/KnownTypesTest.java
- base/src/test/java/io/spine/util/Predicates2Test.java
- license-report.md
- pom.xml
- testlib/src/test/kotlin/io/spine/protobuf/GoogleTypesTest.kt
- version.gradle.kts
This PR adds diagnostic methods for `KnownTypes`.
> Improve diagnostics for `KnownType`

- .idea/misc.xml
- buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
- buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt
- buildSrc/src/main/kotlin/io/spine/internal/gradle/kotlin/KotlinConfig.kt
- license-report.md
- pom.xml
- version.gradle.kts
This PR updates the dependency on Protobuf and applies latest `config`.
> Bump Protobuf and `config`

- base/src/main/kotlin/io/spine/string/Strings.kt
- base/src/main/kotlin/io/spine/util/MoreCollections.kt
- license-report.md
- pom.xml
- version.gradle.kts
This PR fixes visibility of extension functions introduced by the [previous PR](#753).
> Fix `fun` visiblity

- license-report.md
- pom.xml
- version.gradle.kts
This PR triggers the publishing with the new library version.
> [1.x] Trigger publishing

- buildSrc/src/main/kotlin/io/spine/internal/gradle/protobuf/ProtoTaskExtensions.kt
- gradle.properties
- license-report.md
- pom.xml
- version.gradle.kts
This PR adds small fixes to the documentation which did not get into the previous PR.
> Small doc fixes

- README.md
- license-report.md
- pom.xml
- tools/model-compiler/src/main/java/io/spine/tools/compiler/check/DependencyConfigurer.java
- tools/model-compiler/src/test/java/io/spine/tools/compiler/check/DependencyConfigurerTest.java
- tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/SpineProtocTest.java
- version.gradle.kts
This changeset releases `base` artifacts in version 1.9.0.
Other than that, several minor description issues in tests were addressed.
> Release 1.9.0

- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/io/spine/internal/dependency/CheckerFramework.kt
- buildSrc/src/main/kotlin/io/spine/internal/dependency/Dokka.kt
- buildSrc/src/main/kotlin/io/spine/internal/dependency/ErrorProne.kt
- buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt
- buildSrc/src/main/kotlin/io/spine/internal/dependency/Gson.kt
- buildSrc/src/main/kotlin/io/spine/internal/dependency/Guava.kt
- buildSrc/src/main/kotlin/io/spine/internal/dependency/Kover.kt
- buildSrc/src/main/kotlin/io/spine/internal/dependency/Netty.kt
- buildSrc/src/main/kotlin/io/spine/internal/dependency/OsDetector.kt
- buildSrc/src/main/kotlin/io/spine/internal/dependency/Pmd.kt
- buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt
- buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
- buildSrc/src/main/kotlin/io/spine/internal/dependency/Roaster.kt
- buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
- license-report.md
- pom.xml
- src/main/java/io/spine/code/proto/FileDescriptors.java
- src/main/java/io/spine/code/proto/FileSet.java
- src/main/java/io/spine/code/proto/Linker.java
- src/main/java/io/spine/io/Delete.java
- src/main/java/io/spine/type/KnownTypes.java
- version.gradle.kts
This PR updates the dependency on Spine Logging to latest version, addressing the breaking API changes.
External dependencies were also udpated.
> Bump Logging etc.

- dependencies.md
- pom.xml
- src/main/proto/spine/options.proto
- version.gradle.kts
This PR adds a dollar sign to named placeholders in error messages.
> Use Kotlin-like placeholder in error message templates

- base/src/main/java/io/spine/code/fs/AbstractSourceFile.java
- dependencies.md
- pom.xml
- version.gradle.kts
This PR addresses the remaining deprecations after migration to new dependencies and JSpecify.
> Address deprecation
