SpineEventEngine/base

ext.gradle
gradle-plugins/model-compiler/build.gradle
gradle-plugins/model-compiler/src/main/java/io/spine/gradle/compiler/Extension.java
gradle-plugins/model-compiler/src/main/java/io/spine/gradle/compiler/failure/FailureWriter.java
gradle-plugins/model-compiler/src/main/java/io/spine/gradle/compiler/validate/ValidatingBuilderWriter.java
gradle-plugins/model-compiler/src/test/java/io/spine/gradle/compiler/ExtensionShould.java
gradle-plugins/model-compiler/src/test/resources/build.gradle

This PR addresses a few things.
1. The plugins no longer depend on `spine-client-core`. Instead, they depend `spine-base`.
2. The test code depends on `spine-testutil-base` instead of `spine-testutil-core`.
3. `ThrowableMessage` is used for code generation instead of `FailureThrowable`.
4. The generation folder for Spine failures is now set to `... /generated/ (main|test) /spine` instead of ` ... /generated/ (main or test) /java`.
5. The dependency on `tools` module is set to `0.9.25-SNAPSHOT` (the one, where there is no model compiler already).
The version for `base` modules is increased to `0.9.29-SNAPSHOT`.

Migrate to `spine-base` dependency instead of `spine-client-core` + `ThrowableMessage`

---

base/src/test/proto/spine/test/failures.proto
base/src/test/proto/spine/test/identifiers_should.proto
base/src/test/proto/spine/test/json/json_should.proto
base/src/test/proto/spine/test/messages_should.proto
base/src/test/proto/spine/test/option/entity_options_should.proto
base/src/test/proto/spine/test/protobuf/any_packer_should.proto
base/src/test/proto/spine/test/types/known_types_should.proto
base/src/test/proto/spine/test/validate/msg/alt_fields.proto
base/src/test/proto/spine/test/validate/msg/commands.proto
base/src/test/proto/spine/test/validate/msg/messages.proto

Move
```protobuf
import "spine/options.proto";
``` 
at the top of the import section in proto files.

Move `options` to the top of the proto files.

---

base/src/main/java/io/spine/util/Exceptions.java
base/src/main/java/io/spine/util/PropertyFiles.java
base/src/test/java/io/spine/util/ExceptionsShould.java
ext.gradle

This PR:
* Changes return values from `ImmutableSet` to `Set` (with immutability mentioned in Javadocs)
* Adds formatted utility for throwing `UnsupportedOperationException`.
* Advances Spine version to `0.9.43-SNAPSHOT`.

Small API improvements

---

base/src/main/java/io/spine/base/ThrowableMessage.java
base/src/main/java/io/spine/protobuf/MessageField.java
base/src/main/java/io/spine/protobuf/MessageFieldException.java
base/src/test/java/io/spine/base/ThrowableMessageShould.java
base/src/test/java/io/spine/protobuf/MessageFieldExceptionShould.java
base/src/test/java/io/spine/protobuf/MessageFieldShould.java
ext.gradle

This PR
* Introduces `MessageFieldException` is introduced, which improves diagnostics for error cases.
* Adds the ability to set producer ID for a `ThrowableMessage`.

`MessageField` and `ThrowableMessage` improvements

---

gradle-plugins/model-compiler/build.gradle
gradle-plugins/model-compiler/src/main/java/io/spine/gradle/compiler/message/MessageDeclaration.java
gradle-plugins/model-compiler/src/main/java/io/spine/gradle/compiler/message/MessageDeclarations.java
gradle-plugins/model-compiler/src/test/java/io/spine/gradle/compiler/message/MessageDeclarationsShould.java
gradle-plugins/model-compiler/src/test/proto/spine/message/message_declarations_test.proto

This PR fixes work of `MessageDeclarations.find(...)`. Before the change, formation of returned declarations was incorrect.

Fix wrong search of message declarations

---

ext.gradle
gradle-plugins/plugin-base/src/main/java/io/spine/gradle/TaskName.java

This PR adds the tasks in `TaskName` enumeration, that will be used in the plugin for formatting Javadocs in sources generated basing on Protobuf definitions.

Create tasks for usage in `protobuf-javadoc-plugin`

---

.codacy.yaml
.gitignore
base/src/main/proto/spine/options.proto
ext.gradle
gradle-plugins/model-compiler/build.gradle
protoc-plugin/build.gradle
protoc-plugin/plugin_runner.bat
protoc-plugin/plugin_runner.sh
protoc-plugin/src/main/java/io/spine/tools/protoc/MarkerInterfaceGenerator.java
protoc-plugin/src/main/java/io/spine/tools/protoc/MarkerInterfaces.java
protoc-plugin/src/main/java/io/spine/tools/protoc/Plugin.java
protoc-plugin/src/main/java/io/spine/tools/protoc/SpineProtoGenerator.java
protoc-plugin/src/main/java/io/spine/tools/protoc/package-info.java
protoc-plugin/src/test/java/io/spine/tools/protoc/MarkerInterfaceGeneratorShould.java
protoc-plugin/src/test/java/io/spine/tools/protoc/MarkerInterfacesShould.java
protoc-plugin/src/test/proto/spine/tools/protoc/every_is_in_one_file.proto
protoc-plugin/src/test/proto/spine/tools/protoc/every_is_test.proto
protoc-plugin/src/test/proto/spine/tools/protoc/is_in_one_file.proto
protoc-plugin/src/test/proto/spine/tools/protoc/is_test.proto
settings.gradle

This PR is a part of #43 PR which introduces the marker interface generation upon `(is)` and `(every_is)` options.
In order to be run and tested on CI properly, it is split into two separate pull requests.

Protoc plugin module

---

ext.gradle
settings.gradle

This PR brings the integration tests for the `protoc-plugin` module.
The codebase is already present in `master`. Now we only update the `settings.gradle` to include that code into the build.

Protoc plugin integration tests

---

ext.gradle
gradle-plugins/model-compiler/build.gradle
gradle-plugins/model-compiler/spine_protoc.gradle
gradle-plugins/model-compiler/src/main/java/io/spine/gradle/compiler/Extension.java
gradle-plugins/model-compiler/src/test/java/io/spine/gradle/compiler/ExtensionShould.java
gradle-plugins/model-compiler/src/test/java/io/spine/gradle/compiler/given/Given.java
gradle-plugins/plugin-base/src/test/java/io/spine/gradle/GradleProject.java

In this PR:
- `${projectDir}/.spine/` directory is included to the clean directories by default (fixes #47);
- `GradleProject` API enhanced to make it possible to switch the debug mode if required.

Clean Spine directory

---

base/src/main/proto/spine/money/money.proto
ext.gradle

This PR updates the `base` version before the upcoming `0.10.0` release.
Also, it addresses an issue, raised in C++ Spine client library. `Currency.BSD` enum value causes a compile-time conflict with system header `sys/param.h`, which also defines `BSD` in some *nix operating systems. For instance:
```cpp
//...
#define	BSD	199103		/* March, 1991 system version (year & month) */
// ...
```
(_taken from a [random `sys/param.h`](http://unix.superglobalmegacorp.com/Net2/newsrc/sys/param.h.html) in illustrative purposes_)
Therefore `Currency.BSD` was renamed to `Currency.BSD_`.
The library version has been set to `0.9.77-SNAPSHOT`.

Update and cleanup before `0.10.0` release

---

ext.gradle
gradle-plugins/model-compiler/spine_protoc.gradle
gradle-plugins/model-compiler/src/main/java/io/spine/gradle/compiler/Extension.java
gradle-plugins/model-compiler/src/test/java/io/spine/gradle/compiler/ModelCompilerPluginShould.java
gradle-plugins/model-compiler/src/test/java/io/spine/gradle/compiler/SpineProtocShould.java
gradle-plugins/plugin-base/src/test/java/io/spine/gradle/GradleProjectShould.java
gradle-plugins/plugin-base/src/test/java/io/spine/gradle/SpinePluginBuilderShould.java
gradle-plugins/plugin-base/src/test/java/io/spine/gradle/given/Given.java

Fix the `.spine` directory generation name. Because of an error, it was generated as `..spine` (with 2 dot symbols instead of 1).
Also, in this PR we change the logging level in the `Extension` getters and setters from `trace` to `debug`, since `trace` is not visible from the command line.

Fix Spine directory name

---

ext.gradle

In this PR we update the Spine plugin versions.
This PR overrides the `0.10.30-SNAPSHOT` version.

Update dependencies versions

---

ext.gradle
testlib/src/main/java/io/spine/test/DisplayNames.java
testlib/src/test/java/io/spine/test/DisplayNamesShould.java

This PR adds storage for the common JUnit 5 test [display names](https://junit.org/junit5/docs/5.0.3/api/org/junit/jupiter/api/DisplayName.html) to the `testlib` module.
This class can provide assistance in avoiding string literal duplication when assigning `@DisplayName` to the common test cases like null tolerance check or utility constructor check.
`DisplayNames` is represented as a class and not an enumeration because `@DisplayName` annotation requires constant `String` expression as its parameter, so we can't retrieve such expression from enum constant in any reasonable way.
Spine version advances to `0.10.40-SNAPSHOT`.

Add class storing common display names for JUnit 5 tests

---

build.gradle
tools/plugin-testlib/build.gradle

In this PR we configure the `plugin-testlib` module to be published to the Maven repository.
This is required for the tests in `core-java`.

Publish `plugin-testlib`

---

ext.gradle
tools/javadoc-prettifier/src/test/java/io/spine/tools/protodoc/given/ProtoJavadocPluginTestEnv.java
tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/ProtoAnnotatorPluginShould.java
tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/RejectionGenPluginShould.java
tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/SpineProtocShould.java
tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/ValidatingBuilderGenPluginShould.java
tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/ValidationRulesLookupPluginShould.java
tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/given/RejectionTestEnv.java
tools/plugin-testlib/src/main/java/io/spine/tools/gradle/GradleProject.java
tools/plugin-testlib/src/test/java/io/spine/tools/gradle/GradleProjectTest.java

Previously, the `GradleProject` test tool accepted only JUnit 4 [`TemporaryFolder`](https://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html) as the project directory. This caused problems for the tests which were already migrated to the JUnit 5 API.
Now, the interface of the `GradleProject` is changed to accept more generic `File` as the project directory, thus enabling it to be used in both JUnit 4 and JUnit 5 tests.
The Spine version advances to `0.10.45-SNAPSHOT`.

Change `GradleProject` to accept `File` as project directory

---

tools/protoc-plugin/src/main/java/io/spine/tools/protoc/MarkerInterfaceGenerator.java
tools/protoc-plugin/src/main/java/io/spine/tools/protoc/MarkerInterfaceSpec.java
tools/protoc-plugin/src/main/java/io/spine/tools/protoc/MessageAndInterface.java
tools/protoc-plugin/src/main/java/io/spine/tools/protoc/Plugin.java
tools/protoc-plugin/src/main/java/io/spine/tools/protoc/SpineProtoGenerator.java
tools/protoc-plugin/src/test/java/io/spine/tools/protoc/MarkerInterfaceGeneratorShould.java
tools/protoc-plugin/src/test/java/io/spine/tools/protoc/MarkerInterfaceSpecShould.java

This PR provides the following changes for the `protoc-plugin` module:

Remove the unnecessary `final` keyword on local variables for the `protoc-plugin` module.

---

tools/plugin-testlib/src/main/java/io/spine/tools/gradle/GradleProject.java
tools/plugin-testlib/src/test/java/io/spine/tools/gradle/GradleProjectTest.java

This PR provides the following changes for the `plugin-testlib` module:

Remove the unnecessary `final` keyword on local variables for the `plugin-testlib` module

---

tools/plugin-base/src/main/java/io/spine/tools/gradle/GradleTask.java
tools/plugin-base/src/main/java/io/spine/tools/gradle/ProjectHierarchy.java
tools/plugin-base/src/main/java/io/spine/tools/gradle/SpinePlugin.java
tools/plugin-base/src/main/java/io/spine/tools/gradle/TaskDependencies.java
tools/plugin-base/src/test/java/io/spine/tools/gradle/ProjectHierarchyShould.java
tools/plugin-base/src/test/java/io/spine/tools/gradle/SpinePluginBuilderShould.java

This PR provides the following changes for the `plugin-base` module:

Remove the unnecessary `final` keyword on local variables for the `plugin-base` module.

---

tools/reflections-plugin/src/main/java/io/spine/tools/reflections/Extension.java
tools/reflections-plugin/src/main/java/io/spine/tools/reflections/ReflectionsPlugin.java
tools/reflections-plugin/src/test/java/io/spine/tools/reflections/ExtensionShould.java
tools/reflections-plugin/src/test/java/io/spine/tools/reflections/Given.java
tools/reflections-plugin/src/test/java/io/spine/tools/reflections/ReflectionsPluginShould.java

This PR provides the following changes for the `reflections-plugin` module:

Remove the unnecessary `final` keyword on local variables for the `reflections-plugin` module

---

tools/javadoc-prettifier/src/main/java/io/spine/tools/protodoc/BacktickFormatting.java
tools/javadoc-prettifier/src/main/java/io/spine/tools/protodoc/Extension.java
tools/javadoc-prettifier/src/main/java/io/spine/tools/protodoc/JavadocFormatter.java
tools/javadoc-prettifier/src/main/java/io/spine/tools/protodoc/LineFormatting.java
tools/javadoc-prettifier/src/main/java/io/spine/tools/protodoc/PreTagFormatting.java
tools/javadoc-prettifier/src/main/java/io/spine/tools/protodoc/ProtoJavadocPlugin.java
tools/javadoc-prettifier/src/test/java/io/spine/tools/protodoc/BacktickFormattingShould.java
tools/javadoc-prettifier/src/test/java/io/spine/tools/protodoc/JavadocFormatterShould.java
tools/javadoc-prettifier/src/test/java/io/spine/tools/protodoc/LineFormattingShould.java
tools/javadoc-prettifier/src/test/java/io/spine/tools/protodoc/PreTagFormattingShould.java
tools/javadoc-prettifier/src/test/java/io/spine/tools/protodoc/ProtoJavadocPluginShould.java
tools/javadoc-prettifier/src/test/java/io/spine/tools/protodoc/given/ProtoJavadocPluginTestEnv.java

This PR provides the following changes for the `javadoc-prettifier` module:
1. The `final` keyword on local var iables was removed;
2. Guava's `Optional` was replaced with JDK 8 `Optional`.

Replacement of optional for the `javadoc-prettifier` module

---

tools/javadoc-filter/src/main/java/io/spine/tools/javadoc/AnnotationAnalyst.java
tools/javadoc-filter/src/main/java/io/spine/tools/javadoc/ExcludeInternalDoclet.java
tools/javadoc-filter/src/main/java/io/spine/tools/javadoc/ExcludeInternalPrinciple.java
tools/javadoc-filter/src/main/java/io/spine/tools/javadoc/PackageCollector.java
tools/javadoc-filter/src/test/java/io/spine/tools/javadoc/ExcludeInternalDocletShould.java
tools/javadoc-filter/src/test/java/io/spine/tools/javadoc/JavadocArgsBuilder.java
tools/javadoc-filter/src/test/java/io/spine/tools/javadoc/RootDocProxyReceiver.java

This PR provides the following changes for the `javadoc-filter` module:

Remove the unnecessary `final` keyword on local variables for the `javadoc-filter` module

---

ext.gradle
tools/model-compiler/src/main/java/io/spine/tools/compiler/annotation/SourceVisitor.java
tools/model-compiler/src/main/java/io/spine/tools/compiler/validation/ValidationRulesLookup.java
tools/model-compiler/src/test/java/io/spine/tools/compiler/annotation/check/SourceCheck.java

This PR provides the following changes for the `model-compiler` module:
- Guava's `Predicate` was replaced with JDK8 `Predicate`;
- Guava's `Function` was replaced with JDK8 `Function`;
- The version was updated to `0.10.51-SNAPSHOT`.

Replacement of Guava's `Predicate` and `Function` with JDK8 classes

---

.idea/inspectionProfiles/Project_Default.xml
base/src/main/java/io/spine/util/Preconditions2.java
base/src/main/java/io/spine/util/Suppliers2.java
base/src/test/java/io/spine/base/EnvironmentShould.java
base/src/test/java/io/spine/util/Preconditions2Test.java
base/src/test/java/io/spine/util/Suppliers2Test.java
ext.gradle
testlib/src/main/java/io/spine/testing/UtilityClassTest.java

This PR:
* Introduces `Suppliers2` utility which adapts Guava `Supplier`s to those from Java 8.
* Adds `UtilityClassTest` test class base.
Spine version advances to `0.10.53-SNAPSHOT`.

Supplier adapters

---

.idea/inspectionProfiles/Project_Default.xml
base/src/test/java/io/spine/base/TimeTest.java
base/src/test/java/io/spine/base/given/ConstantTimeProvider.java
base/src/test/java/io/spine/base/given/GivenDurations.java
ext.gradle
testlib/build.gradle

This PR adds Google Truth into dependencies, and migrates `TimeTest` to using this assertion framework.

Adopt Google Truth

---

base/src/main/java/io/spine/code/proto/FileDescriptors.java
ext.gradle

In this PR we remove overly large and redundant logging of `.desc` files lookup.
This problem is a blocker since Travis cannot build `core-java` with `--debug` option in Gradle—the log size is over 4 MB.

Remove redundant logging

---

base/build.gradle
build.gradle
tools/model-compiler/build.gradle
tools/protoc-plugin/build.gradle

In this PR we remove the redundant generated classes. 
Before, all the `google.protobuf` and `spine.base` definitions were converted into Java in some modules tests. This might be leftovers from some kind of a debug process. Now, this code generation is not done anymore.
Also, since now all the `generated` directories are deleted on `:clean`.

Remove Redundant Code Generation

---

base/src/main/java/io/spine/type/MessageClass.java
base/src/main/java/io/spine/validate/ConstraintViolations.java
base/src/test/java/io/spine/type/MessageClassTest.java

Since recently, `MessageClass` is parametrized with a type of the stored message type.
In this PR we change the signature of the constructor from `MessageClass(Class<M> value)` to `MessageClass(Class<? extends M> value)`, so that the extended classes have some wiggle room.
Also, the signature of `ExceptionFactory` was changed to allow any kinds of `MessageClass`-es, regardless of the wrapper type.

Fix `MessageClass` Interface

---

ext.gradle
testlib/src/main/java/io/spine/testing/logging/MemoizingStream.java
testlib/src/main/java/io/spine/testing/logging/MuteLogging.java
testlib/src/main/java/io/spine/testing/logging/MuteLoggingExtension.java
testlib/src/test/java/io/spine/testing/logging/MemoizingStreamTest.java
testlib/src/test/java/io/spine/testing/logging/MuteLoggingExtensionTest.java
testlib/src/test/java/io/spine/testing/logging/MuteLoggingTest.java

In this PR we introduce a test utility for turning off a particular test logging.
To mute a test case or a test suite, mark it with the `@MuteTests` annotation.

Mute Tests

---

base/src/main/java/io/spine/code/java/DefaultJavaProject.java
ext.gradle
testlib/src/main/java/io/spine/testing/Tests.java
testlib/src/test/java/io/spine/testing/TestsShould.java
testlib/src/test/java/io/spine/testing/logging/MuteLoggingExtensionTest.java
tools/plugin-testlib/src/main/java/io/spine/tools/gradle/GradleProject.java
tools/proto-js-plugin/src/main/java/io/spine/js/generate/JsFileWriter.java
tools/proto-js-plugin/src/main/java/io/spine/js/generate/field/parser/primitive/PrimitiveParser.java
tools/proto-js-plugin/src/test/java/io/spine/js/generate/given/FileWriters.java
tools/reflections-plugin/src/main/java/io/spine/tools/reflections/ReflectionsPlugin.java

This PR fixes the way field masks are created and checked. Previously, we assumed that field masks contain full field names. The standard `FieldMaskUtil` creates masks with short names.
This PR also addresses Error Prone and Javadoc warnings.

Fix field masks

---

base/src/main/java/io/spine/base/Identifier.java
base/src/main/java/io/spine/base/UuidMessage.java
base/src/test/java/io/spine/base/IdentifierTest.java
base/src/test/proto/spine/test/identifiers_should.proto
version.gradle

This PR fixes #206.
Now, it is possible to generate a so-called `UuidMessage` using `Identifier`. The message is a Protobuf `Message` with a single string field named `uuid`. During the generation, the `uuid` field is filled with a value obtained from `Identifier.newUuid()`.
So, if you have a message like:
```proto
message SessionId {
string uuid = 1;
}
```
You can generate it in this way:
```java
SessionId id = Identifier.generate(SessionId.class);
```
If a message doesn't match the requirements, an exception is thrown.
The framework version was bumped to `0.11.9-SNAPSHOT`.

Generate a UUID message using `Identifier`

---

base/src/main/java/io/spine/code/proto/Option.java
base/src/main/java/io/spine/validate/BooleanFieldValidator.java
base/src/main/java/io/spine/validate/ByteStringFieldValidator.java
base/src/main/java/io/spine/validate/EmptyMapFieldValidator.java
base/src/main/java/io/spine/validate/EnumFieldValidator.java
base/src/main/java/io/spine/validate/FieldDeclaration.java
base/src/main/java/io/spine/validate/FieldValidator.java
base/src/main/java/io/spine/validate/FloatFieldValidatorBase.java
base/src/main/java/io/spine/validate/IntegerFieldValidator.java
base/src/main/java/io/spine/validate/LongFieldValidator.java
base/src/main/java/io/spine/validate/MessageFieldValidator.java
base/src/main/java/io/spine/validate/NumberFieldValidator.java
base/src/main/java/io/spine/validate/StringFieldValidator.java
base/src/main/java/io/spine/validate/rule/ValidationRule.java
base/src/main/java/io/spine/validate/rule/ValidationRuleOptions.java
base/src/main/java/io/spine/validate/rule/ValidationRules.java
base/src/main/java/io/spine/validate/rule/package-info.java
base/src/test/java/io/spine/validate/FieldValidatorShould.java
base/src/test/java/io/spine/validate/MessageValidatorTest.java
base/src/test/proto/spine/test/validate/messages.proto
tools/model-compiler/src/main/java/io/spine/tools/compiler/validation/ValidationRulesLookup.java
tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/ValidationRulesLookupPluginShould.java
version.gradle

This PR fixes #179.
Now, the framework assumes, that an entity ID is required by default.
The only way to say that an entity ID is not required is to explicitly mark it as `[(required)=false]`.
A field is considered an entity ID if:
- The name is `id` or ends with `_id`.
- The field if the first in a containing message.
- A message containing the field has `(entity).kind` option set.
The version was bumped to `0.11.10-SNAPSHOT`.

Assume entity IDs required by default

---

tools/javadoc-prettifier/build.gradle
version.gradle

This PR fixes #213.
The redundant `javadoc-prettifier` artifact was published by `java-gradle-plugin`. The plugin is not applied not since it isn't required. Instead, a dependency on `gradleTestKit` was added.
The version was bumped to `0.11.11-SNAPSHOT`.

Don't publish duplicated `javadoc-prettifier` artifact

---

base/src/main/java/io/spine/base/Identifier.java
base/src/main/java/io/spine/protobuf/TypeConverter.java
base/src/main/java/io/spine/string/Stringifiers.java
base/src/main/java/io/spine/validate/AbstractValidatingBuilder.java
base/src/test/java/io/spine/base/IdentifierTest.java
base/src/test/java/io/spine/json/JsonTest.java
base/src/test/java/io/spine/protobuf/AnyPackerTest.java
base/src/test/java/io/spine/protobuf/MessageFieldTest.java
base/src/test/java/io/spine/protobuf/TypeConverterTest.java
base/src/test/java/io/spine/validate/AbstractValidatingBuilderTest.java
base/src/test/java/io/spine/validate/MessageValidatorTest.java
testlib/src/main/java/io/spine/testing/Tests.java
version.gradle

This PR fixes #200, #201.
The API Changes:
- `Stringifiers.fromString(...)` now takes `Class` instead of `Type`.
- `Identifier.unpack(Any)` now returns `Object`. If a result type is important, use `Identifier.unpack(Any, Class)`.
- `TypeConverter.toMessage(Object)` now returns `Message`. If a result type is important , use `TypeConverter.toMessage(Object, Class)`.
- `AbstractValidatingBuilder.convert(...)` now takes `Class` instead of `Type`.
The version was bumped to `0.11.13-SNAPSHOT`.

Get rid of unused type parameters in formal parameters

---

base/src/main/java/io/spine/validate/FieldValue.java
tools/smoke-tests/build.gradle

A `FieldValue` determines the Java type of its value by the field descriptor: if the field is `repeated`, the value is assumed to be a `List`.
However, when a `ValidatingBuilder` validates a value received in an `add<Field>` method (an item added to a repeated field), the runtime de-facto value is not of type `List` but of the field type, e.g. a message.
From now, `FieldValue` checks the actual Java type of the value instead of the descriptor.

Fix a ClassCastException in FieldValue

---

tools/protoc-plugin/src/main/java/io/spine/tools/protoc/SpineProtoGenerator.java
tools/protoc-plugin/src/test/java/io/spine/tools/protoc/MarkerInterfaceGeneratorTest.java
tools/protoc-plugin/src/test/proto/spine/tools/protoc/user.proto
tools/protoc-plugin/src/test/proto/spine/tools/protoc/user_name.proto

Before, we tried to generate marker interfaces and insertion points for Protobuf sources which are _included_ for a Proto compilation but are not requested, i.e. Protobuf imports. This led to failures in multi-project Gradle builds when several projects depending on each other had some marker interfaces to generate.
From now, the markers are generated for the requested types only.

Skip imports when generating marker interfaces

---

base-validating-builders/build.gradle
base/build.gradle
base/src/main/java/io/spine/code/AbstractSourceFile.java
base/src/main/java/io/spine/code/java/DefaultJavaProject.java
base/src/main/java/io/spine/code/proto/Directory.java
base/src/main/java/io/spine/code/proto/MessageType.java
base/src/test/java/io/spine/code/proto/MessageTypeTest.java
build.gradle
tools/model-compiler/README.md
tools/model-compiler/spine-protoc.gradle.template
tools/model-compiler/src/main/java/io/spine/tools/compiler/annotation/Annotator.java
tools/model-compiler/src/main/java/io/spine/tools/compiler/validation/SingularFieldMethods.java
tools/model-compiler/src/main/java/io/spine/tools/compiler/validation/VBuilderGenerator.java
tools/model-compiler/src/main/java/io/spine/tools/compiler/validation/VBuilderMethods.java
tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/ErrorProneChecksExtension.java
tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/Extension.java
tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/ModelCompilerPlugin.java
tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/Severity.java
tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/ValidatingBuilderGenPlugin.java
tools/model-compiler/src/test/java/io/spine/tools/compiler/validation/VBuilderCodeTest.java
tools/model-compiler/src/test/proto/spine/test/tools/validation/builder/nested.proto
tools/model-compiler/src/test/proto/spine/test/tools/validation/builder/top_level.proto
tools/smoke-tests/known-types-tests/build.gradle

This PR migrates generation of Validating Builders of types defined in the `base`  from dependency on locally deployed JAR to dependencies to interim artifacts. 
The primary purpose of this change is to avoid double dependency on both source code of the `base` module, and classes from the locally deployed artifact.
The notable fix in this PR is restored filtering of proto types by the module which declares them.

Simplify dependency for generation of vbuilders for `base`

---

tools/protoc-api/build.gradle

Previously, the `spine-protoc-api` artifact was published under auto-assigned `spine-base` group.
This caused problems with dependent repositories build.

Set `protoc-api` publish group to `io.spine.tools`

---

tools/model-compiler/src/main/java/io/spine/tools/compiler/validation/VBuilderCode.java
tools/model-compiler/src/main/java/io/spine/tools/compiler/validation/VBuilderMethods.java

This PR closes https://github.com/SpineEventEngine/base/issues/292.
Before, all generated `mergeFrom` methods were malformed.
This PR fixes it, making the generated code look as expected.
It also extracts a `Splitter` creation from a loop to a `static final` field, since creating multiple `Splitters` is pointless.

Validating builders `mergeFrom` method formatting fix

---

base/src/main/java/io/spine/base/Identifier.java
base/src/main/java/io/spine/base/UuidFactory.java
base/src/main/java/io/spine/logging/Logging.java
base/src/main/java/io/spine/reflect/PackageGraph.java
base/src/main/java/io/spine/validate/ComparableNumber.java
build.gradle
testlib/src/main/java/io/spine/testing/UtilityClassTest.java
tools/model-compiler/src/main/java/io/spine/tools/compiler/annotation/ApiOption.java
tools/model-compiler/src/main/java/io/spine/tools/compiler/annotation/ModuleAnnotator.java
tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/Extension.java
tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/GeneratedInterfaces.java
tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/PostfixInterfaceConfig.java
tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/ProtocConfigurationPlugin.java
tools/plugin-base/src/main/java/io/spine/tools/gradle/GradleTask.java
tools/plugin-base/src/main/java/io/spine/tools/type/MergedDescriptorSet.java
tools/proto-js-plugin/src/main/java/io/spine/js/generate/field/parser/FieldParser.java

This PR enables the PMD code analysis for `base` modules.
Some warnings were suppressed and some violations were addressed.
Checkstyle rules aren't enabled with this PR due to the https://github.com/checkstyle/checkstyle/issues/3238, which causes Checkstyle to crash on `LogMessages` with `@Nullable ... params`.

Enable PMD static analysis during the build

---

tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/ProtocConfigurationPlugin.java

Currently the version updates of Spine dependencies aren't possible. With the updated versions of Gradle plugins something will change. In particular, the way Protoc plugin attempts to modify a list of Gradle tasks while iterating through the same list. 
So basically instead of inserting an element into a collection being traversed, this PR changes the way we treat a collection. And before iterating through tasks, we create a copy of the Gradle task collection and use it for iteration.

Make a copy of "live" view on Gradle tasks in Protoc plugin before iterating through them

---

.gitattributes
.idea/dictionaries/common.xml
base/src/main/java/io/spine/code/proto/FieldDeclaration.java
base/src/main/java/io/spine/validate/AbstractValidatingBuilder.java
tools/model-compiler/src/main/java/io/spine/tools/compiler/validation/AbstractMethodGroup.java
tools/model-compiler/src/main/java/io/spine/tools/compiler/validation/MapFieldMethods.java
tools/model-compiler/src/main/java/io/spine/tools/compiler/validation/RepeatedFieldMethods.java
tools/model-compiler/src/main/java/io/spine/tools/compiler/validation/SingularFieldMethods.java
tools/model-compiler/src/main/java/io/spine/tools/compiler/validation/VBuilderMethods.java
tools/smoke-tests/validation-tests/src/test/java/io/spine/test/validate/ValidatingBuilderTest.java

Currently, an enabled `(set_once)` option forbids the user to set any kind of value to the field. This is inconvenient since sometimes users may want to set the same value to the field. The `hasField(...)` checks are the only way to make sure that an error would not be produced in such a case.
This PR allows users to set the same value to the field.
Also, the `(set_once)` checks are being added to `setRaw...(...)` and `clear...()` methods.
`put...(...)` and `add...(...)` methods now have explicit checks that the collection field is not marked with `(set_once)`.

Allow set same value if `(set_once) = true`

---

tools/plugin-base/src/main/java/io/spine/tools/gradle/TaskName.java

Some of the elements of `TaskName` enum were not documented. In this PR we add the required doc.
Fixes #352.

Document task names

---

base/src/main/java/io/spine/reflect/PackageGraph.java

This PR updates the `config` submodule reference to the latest one — in order to grab all the latest dependency updates.
Also, it updates the `PackageGraph` to the latest Guava API.

Update the reference to `config` to grab the forced Gradle Protobuf plugin version

---

tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/ProtocConfigurationPlugin.java
tools/protoc-plugin/src/main/java/io/spine/tools/protoc/Plugin.java
tools/protoc-plugin/src/test/java/io/spine/tools/protoc/PluginTest.java
tools/protoc-plugin/src/test/java/io/spine/tools/protoc/SpineProtoGeneratorTest.java
tools/protoc-plugin/src/test/java/io/spine/tools/protoc/given/CodeGeneratorRequestGiven.java

This PR fixes #379.
Now Spine Protoc Plugin parameters are base64-encoded.

Encode Spine Protoc Plugin custom parameters

---

base/src/main/java/io/spine/validate/FieldValidator.java
base/src/main/java/io/spine/validate/OneofValidator.java
base/src/main/java/io/spine/validate/RequiredFieldConstraint.java
base/src/test/java/io/spine/validate/MessageValidatorTest.java
base/src/test/java/io/spine/validate/OneofTest.java
base/src/test/java/io/spine/validate/RequiredFieldTest.java
base/src/test/proto/spine/test/validate/oneof.proto
base/src/test/proto/spine/test/validate/required_field_test.proto

This PR partially addresses #378.
Now `oneof` fields are optional by default.
The configuration validation will be implemented in a separate PR.

Fix OneofValidator

---

.codacy.yaml
.travis.yml
base/build.gradle
base/script/protobuf.gradle
build.gradle

This PR configures Gradle to exclude Google `.proto` sources and files generated from those sources from all the Spine archives (such as the default JAR, the source code JAR, and the Javadoc JAR).
Fixes #199.
Also, in this PR we delete the script and configuration files of Codacy.

Exclude Google `.proto`s from artifacts

---

base/script/protobuf.gradle
base/src/main/java/io/spine/validate/MessageFieldValidatingOption.java
base/src/main/java/io/spine/validate/MessageFieldValidator.java
base/src/main/java/io/spine/validate/Valid.java

In this PR we prune the code generated from the Google `.proto` files as soon as it is generated.
We still need to feed `protoc` with the Google `.proto` files in order to receive correct descriptor files.
Fixes #246.
Also, in this PR we clean up the signature of `Valid` option accessor class.

Delete generated Google `.proto`s

---

base/src/main/java/io/spine/annotation/GeneratedMixin.java
base/src/main/java/io/spine/base/MessageContext.java
base/src/main/proto/spine/options.proto
base/src/test/java/io/spine/base/GeneratedMixinTest.java
base/src/test/java/io/spine/base/MessageContextTest.java

This PR introduces `GeneratedMixin` annotation for annotating interfaces that extend generated code with `default` methods declared in the interfaces.

`GeneratedMixin` annotation

---

base/src/main/java/io/spine/base/SerializableMessage.java

This PR removes `@Internal` annotation from `SerializableMessage`. This interface is used in `core-java` for binding generic parameters. So we cannot hide it.

`SerializableMessage` as part of API

---

tools/plugin-base/src/main/java/io/spine/tools/gradle/ConfigurationName.java

This PR adds more Gradle Java plugin configuration names to allow `io.spine.tools.gradle.project.Dependant` class users to call `depend(ConfigurationName configurationName, String notation)` with more options to choose from.

Add missing Gradle Java plugin configuration names.

---

base-validating-builders/build.gradle
license-report.md
testlib/build.gradle
tools/errorprone-checks/src/main/java/io/spine/tools/check/methodresult/ValidatingBuilderWhich.java
tools/errorprone-checks/src/test/resources/io/spine/tools/check/methodresult/given/HandleMethodResultNegatives.java
tools/model-compiler/build.gradle
tools/smoke-tests/README.md
tools/smoke-tests/known-types-tests/build.gradle

This PR replaces hard-coded dependencies with the ones from the `config` submodule where possible.
Also, this PR fixes a minor issue in `HandleMethodResult` check, where `remove...` methods were not considered builder setters. This is needed to build the `web`.

Minor Gradle sources polishing

---

base/src/main/java/io/spine/validate/ComparableNumber.java
base/src/main/java/io/spine/validate/NumberFieldValidator.java
base/src/main/java/io/spine/validate/NumberText.java
base/src/main/java/io/spine/validate/option/Max.java
base/src/main/java/io/spine/validate/option/MaxConstraint.java
base/src/main/java/io/spine/validate/option/Min.java
base/src/main/java/io/spine/validate/option/MinConstraint.java
base/src/main/java/io/spine/validate/option/NumberConversionChecker.java
base/src/main/java/io/spine/validate/option/Range.java
base/src/main/java/io/spine/validate/option/RangeConstraint.java
base/src/main/java/io/spine/validate/option/RangedConstraint.java
base/src/test/java/io/spine/validate/ComparableNumberTest.java
base/src/test/java/io/spine/validate/NumberTextTest.java
base/src/test/java/io/spine/validate/option/NumberConversionCheckerTest.java
base/src/test/java/io/spine/validate/option/RangeTest.java
base/src/test/proto/spine/test/validate/test_range_option.proto
license-report.md
pom.xml
tools/protoc-plugin/src/test/java/io/spine/tools/protoc/PluginTest.java

This PR fixes #436.
The boundaries are now cast to the actual number type that is under validation. Such a cast allows us to have a unified number model for the boundaries and apply them to various numeric types just as Java does it for automatic primitive numbers conversions.

Fix `(range)` option boundaries

---

appveyor.yml

This PR adjust Appveyor configuration to avoid building a branch when there is open PR for it.

Avoid building branch and PR by Appveyor

---

.idea/misc.xml
base/src/main/java/io/spine/base/Environment.java
base/src/main/java/io/spine/logging/LoggerClassValue.java
base/src/test/java/io/spine/base/EnvironmentTest.java
tools/protoc-plugin/src/main/java/io/spine/tools/protoc/iface/InterfaceGenerator.java

This PR:
* Deprecates `Environment.getInstance()` in favor of `instance()`.
* Improves documentation of `InterfaceGenerator` class.

Improve `Environment` accessor name and `InterfaceGenerator ` Javadocs

---

.idea/misc.xml
testlib/src/main/java/io/spine/testing/SlowTest.java

The repository, as well as in the others, contains a number of slow functional tests. When building the project, it is not always necessary to run those tests.
This PR introduces the `@SlowTest` annotation. The annotation marks slow test cases/classes in order for the test runner to exclude them from the default build process.
The respective [Gradle configuration](https://github.com/SpineEventEngine/config/pull/76) is added to the `config` repository in order to apply it where it's needed.

Slow tests annotation

---

base/src/main/java/io/spine/base/Errors.java
base/src/test/java/io/spine/base/ErrorsTest.java

`Errors` utility converts Java's `Throwable`s into `spine.base.Error`s. 
If a given `Throwable` was caused by a constraint violation, the resulting `Error` should reflect that.

 Convert ValidationExceptions into Errors with ValidationError

---

testlib/src/main/java/io/spine/testing/SubjectTest.java
testlib/src/main/java/io/spine/testing/logging/LogRecordSubject.java
testlib/src/test/java/io/spine/testing/logging/LogRecordSubjectTest.java

This PR:
* Adds `SubjectTest` which was previously used in tests of `core-java`.
* Extends `LogRecordSubject` with
* the assertion for  a `Throwable` associated with the `LogRecord` under the test.
* `isError()` assertion.

Extend testlib

---

license-report.md
pom.xml
version.gradle

This PR updates the version of modules to `1.0.1` so that the first maintenance release of Spine had the same version across all libraries.

Update the version to `1.0.1`

---

.travis.yml
base/src/test/java/io/spine/base/TimeTest.java
gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat
license-report.md
pom.xml
testlib/src/main/java/io/spine/testing/SubjectTest.java
testlib/src/main/java/io/spine/testing/logging/LogRecordSubject.java
testlib/src/main/java/io/spine/testing/logging/LogTruth.java
tools/plugin-testlib/src/main/java/io/spine/tools/gradle/testing/TaskSubject.java
tools/protoc-api/src/test/java/io/spine/tools/protoc/PatternSelectorsTest.java
tools/protoc-plugin/build.gradle
tools/smoke-tests/build.gradle
tools/smoke-tests/gradle/wrapper/gradle-wrapper.properties
tools/smoke-tests/gradlew
tools/smoke-tests/gradlew.bat
version.gradle

In this PR we update the dependencies versions:
- Google Truth is updated to `1.0`;
- Gradle is updated to `5.6.1`.

Update Gradle and Truth

---

.idea/dictionaries/common.xml
base/src/main/java/io/spine/protobuf/Messages.java
base/src/main/java/io/spine/reflect/Types.java
base/src/main/java/io/spine/string/EnumStringifier.java
base/src/main/java/io/spine/string/StringifierRegistry.java
base/src/main/java/io/spine/string/Stringifiers.java
base/src/test/java/io/spine/protobuf/MessagesTest.java
base/src/test/java/io/spine/reflect/TypesTest.java
base/src/test/java/io/spine/reflect/given/TypesTestEnv.java
base/src/test/java/io/spine/reflect/given/package-info.java
base/src/test/java/io/spine/string/EnumStringifierTest.java
base/src/test/java/io/spine/string/StringifiersTest.java
base/src/test/proto/spine/test/string/stringifiers_test.proto
tools/proto-js-plugin/src/test/java/io/spine/js/generate/AppendTypeUrlGetterTest.java
version.gradle

This PR fixes `Stringifiers.toString(...)` throwing an exception on receiving an `enum` value.
The `enum` values were not supported because the `EnumStringifier` was actually abstract and was intended for inheritance only. It was done so because the `EnumStringifier` is a `SerializableStringifier` and all serializable stringifiers are persisted as singletons. But it's impossible to persist an arbitrary enum stringifier as a singleton.
This PR makes an `EnumStringifier` a concrete class which is still a `SerializableStringifier` but is not persisted as a singleton (but rather as an ordinary serializable object).

Fix `Stringifiers.toString(...)` not processing enum values

---

license-report.md
pom.xml
tools/plugin-base/src/main/java/io/spine/tools/gradle/Artifact.java
tools/plugin-base/src/main/java/io/spine/tools/gradle/project/Dependant.java
tools/plugin-base/src/main/java/io/spine/tools/gradle/project/DependantProject.java
tools/plugin-base/src/test/java/io/spine/tools/gradle/project/ProjectDependantTest.java
tools/plugin-testlib/src/main/java/io/spine/tools/gradle/testing/MemoizingDependant.java
tools/plugin-testlib/src/test/java/io/spine/tools/gradle/testing/MemoizingDependantTest.java
version.gradle

This PR is a part of https://github.com/SpineEventEngine/bootstrap/pull/30.
The `Dependant` is expanded with `force(...)` and `removeForcedDependency(...)` methods which allow to force the required dependency version and remove the forced dependency from the project respectively.
Spine version is updated to `1.0.2`.

Allow to force individual dependency versions in `Dependant`

---

license-report.md
pom.xml
testlib/src/main/java/io/spine/testing/Tests.java
testlib/src/test/java/io/spine/testing/TestsTest.java
version.gradle

This PR adds the `halt()` method which fails test environment methods that should never be called.
Previously the method was the part of `core-java` test environments.
The version is bumped to `1.0.3-SNAPSHOT`.

Failure utility for methods that should never be called

---

base/src/main/java/io/spine/base/Field.java
base/src/main/java/io/spine/type/TypeName.java
base/src/test/java/io/spine/base/FieldTest.java

This PR fixes obtaining Java enum value from a message field. Previously, `EnumValueDescriptor` was returned, which was not what users would expect.

Enum values

---

base-validating-builders/build.gradle
license-report.md
pom.xml
version.gradle

This PR does the release of library version `1.1.2`.
It also removes the remainder of SLF4J dependencies from the project.

Release `1.1.2`

---

license-report.md
tools/errorprone-checks/build.gradle
tools/javadoc-filter/build.gradle
tools/javadoc-prettifier/build.gradle
tools/mute-logging/build.gradle
tools/proto-dart-plugin/build.gradle
tools/proto-js-plugin/build.gradle
tools/protoc-api/build.gradle
tools/protoc-plugin/build.gradle

A group ID for the `proto-dart-plugin` was not specified, so the tool assumed the root project name by default. In this PR we classify the plugin into the `io.spine.tools` group.

Fix group ID for Proto Dart plugin

---

tools/model-compiler/src/main/java/io/spine/tools/compiler/check/DependencyConfigurer.java
version.gradle

This PR removes the build number made with the `+number` notation because it is not compatible with Maven client.

Remove build number in the version

---

base/src/main/java/io/spine/util/Preconditions2.java
base/src/test/java/io/spine/util/Preconditions2Test.java
pom.xml
version.gradle

This PR fixes treating custom messages passed to precondition checks on `null` values. Previously, formatted messages were used only on non-null values, which could be misleading.
Version bumped to 1.1.7.

Pass custom messages to null checks

---

build.gradle
license-report.md
settings.gradle
tools/proto-dart-plugin/src/main/java/io/spine/generate/dart/ProtoDartPlugin.java

The `proto-dart-plugin` is now included in the build again. The plugin does not require a Dart environment and thus can stay in this repository, along with all the other Gradle plugins.
Also, this PR enables tasks added by `ProtoDartPlugin` to be triggered by `assemble`.

Include `proto-dart-plugin`

---

license-report.md
pom.xml
tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/Extension.java
tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/ProtocPluginConfiguration.java
tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/ProtocPluginConfigurationTest.java
tools/plugin-testlib/src/main/java/io/spine/tools/gradle/testing/BuildGradle.java
tools/protoc-api/src/main/proto/spine/tools/protoc/config.proto
tools/protoc-plugin/src/main/java/io/spine/tools/protoc/NoOpGenerator.java
tools/protoc-plugin/src/main/java/io/spine/tools/protoc/Plugin.java
tools/protoc-plugin/src/test/java/io/spine/tools/protoc/builder/BuilderGeneratorTest.java
tools/protoc-plugin/src/test/proto/spine/tools/protoc/builder/builder_test.proto
version.gradle

In this PR we allow disabling `ValidatingBuilder` generation in the model compiler plugin.
This is needed for the users who don't use Spine framework as a whole, but only the tools from this repository.
In order to disable the feature, configure the plugin as follows:
```gradle
modelCompilder {
generateValidatingBuilders = false
}
```
The value of `generateValidatingBuilders` is `true` by default.

Allow skipping validating builder generation

---

base/src/main/java/io/spine/base/EntityState.java
license-report.md
pom.xml
tools/protoc-api/src/main/java/io/spine/tools/protoc/EntityState.java
tools/protoc-api/src/main/java/io/spine/tools/protoc/GeneratedInterfaces.java
tools/protoc-api/src/main/java/io/spine/tools/protoc/MessageSelector.java
tools/protoc-api/src/main/java/io/spine/tools/protoc/MessageSelectorFactory.java
tools/protoc-api/src/main/java/io/spine/tools/protoc/PatternSelector.java
tools/protoc-api/src/main/java/io/spine/tools/protoc/PrefixSelector.java
tools/protoc-api/src/main/java/io/spine/tools/protoc/ProtocTaskConfigs.java
tools/protoc-api/src/main/java/io/spine/tools/protoc/RegexSelector.java
tools/protoc-api/src/main/java/io/spine/tools/protoc/Selector.java
tools/protoc-api/src/main/java/io/spine/tools/protoc/SuffixSelector.java
tools/protoc-api/src/main/java/io/spine/tools/protoc/UuidMessage.java
tools/protoc-api/src/main/proto/spine/tools/protoc/config.proto
tools/protoc-api/src/test/java/io/spine/tools/protoc/MessageSelectorFactoryTest.java
tools/protoc-api/src/test/java/io/spine/tools/protoc/ProtocTaskConfigsTest.java
tools/protoc-plugin/src/main/java/io/spine/tools/protoc/iface/GenerateEntityStateInterfaces.java
tools/protoc-plugin/src/main/java/io/spine/tools/protoc/iface/InterfaceGenerator.java
tools/protoc-plugin/src/test/java/io/spine/tools/protoc/given/SpineProtocConfigGiven.java
tools/protoc-plugin/src/test/java/io/spine/tools/protoc/iface/GenerateEntityStateInterfacesTest.java
tools/protoc-plugin/src/test/proto/spine/tools/protoc/iface/entity_states.proto
version.gradle

This PR adds a new marker interface for the messages representing entity state.
From now on, all messages marked as `(entity)` of some kind will be marked as `EntityState`. 
They can thus be distinguished from the generic messages and other message types such as `EventMessage` e.g. when creating method overloads.
The interface which is applied to all entity state messages can be configured as follows:
```gradle
modelCompiler {
interfaces {
mark messages().entityState(), asType("some.custom.EntityState")
}
}
```
Please note, that just like for all other marker interface types, the specified custom interface should extend the `io.spine.base.EntityState` interface which is used by default.
Spine version advances to `1.2.0`.

`EntityState` marker interface

---

base/src/main/java/io/spine/base/Field.java
base/src/test/java/io/spine/base/FieldTest.java
license-report.md
pom.xml
version.gradle

This PR extends the `Field` with some utilities needed by the [core-java#1197](https://github.com/SpineEventEngine/core-java/pull/1197).
Spine `base` version advances to `1.2.3`.

Extend the `Field` utility with `presentIn(...)` and `isNested()` methods

---

base/src/main/proto/spine/options.proto
base/src/test/java/io/spine/validate/given/MessageValidatorTestEnv.java

Message values and validation parameters look more distinct when wrapped into backticks:
```
The field 'foo' can only be set when the field 'bar' is defined.
```
VS
```
The field `foo` can only be set when the field `bar` is defined.
```

Change single quotes to backticks in error messages

---

base/build.gradle
build.gradle
license-report.md
pom.xml
tools/model-compiler/build.gradle
tools/model-compiler/src/test/java/io/spine/tools/compiler/check/DependencyConfigurerTest.java
tools/protoc-plugin/build.gradle
tools/validation-generator/build.gradle
version.gradle

This PR removes the usages of `maven` plugin.
The plugin hasn't been used for publishing for a long time, if ever. However, the build relied heavily on the side effects caused by applying the plugin. For example, the plugin also applied `java` which was required by unrelated configurations (such as `jacoco.gradle`).
Now, the plugin is not used and the side effects are reached by more explicit ways, e.g. applying the `base` plugin.
The version of `base` is bumped to 1.3.2, primarily to make sure that publishing is not broken.

Remove `maven` Gradle plugin

---

base/src/main/java/io/spine/base/Time.java
base/src/test/java/io/spine/base/TimeTest.java
license-report.md
pom.xml
version.gradle

This PR brings the emulation of nanoseconds to the system `Time` provider and removes the `ThreadLocal`ity of the `Time.Provider`.
**Emulated nanos**
In most cases, the JVM and underlying OS provides the millisecond-level precision at best. Even with the [changes in JDK 9](https://bugs.openjdk.java.net/browse/JDK-8068730) the precision is improved to microseconds.
Therefore, the messages produced in such a virtual machine are often stamped with the same time value. However, most of the message-ordering routines require distinct time values for proper work.
This PR brings changes that emulate the ticking nanoseconds and provide incremental for the consecutive calls of `currentTime()`.
The returned nanosecond value starts at `0` and never exceeds `999 999`. It is designed to keep the …

System time with emulated nanoseconds

---

base/src/main/java/io/spine/reflect/Methods.java
base/src/test/java/io/spine/reflect/MethodsTest.java
base/src/test/java/io/spine/reflect/given/MethodsTestEnv.java
license-report.md
pom.xml
version.gradle

This PR adds a utility for converting an arbitrary `java.lang.reflect.Method` into a `java.lang.invoke.MethodHandle`.
With `MethodHandles`, we do not have to change the accessibility attribute upon each invocation.

`Method` to `MethodHandle`

---

base/src/main/java/io/spine/base/Time.java
base/src/test/java/io/spine/base/TimeTest.java
license-report.md
pom.xml
version.gradle

Previously, the `Time.currentTime()` by default returned the time with the appended nanosecond value. The framework emulated the nanoseconds to guarantee the distinct values of `Timestamp`s returned for consecutive calls.
However, as it turns out, the storage systems (such as Google Cloud Datastore) do not support nanoseconds in their native types (e.g. `TimestampValue` of Datastore Java client). Instead of storing the `Timestamp` along with the nanoseconds, they round the nanoseconds to the nearest microsecond.
As we want to be using native storage types and have all their features at our disposal — instead of using `long`s to store time values, this PR changes the nanosecond emulation. In particular:
* the emulated nanoseconds are incremented by `1000` for each call, effectively adding …

Make the emulated nanosecond time to increase with microsecond steps

---

base/src/main/java/io/spine/logging/Logging.java
base/src/test/java/io/spine/logging/LoggingTest.java
license-report.md
pom.xml
version.gradle

In this PR we add the `Logging.loggerFor(Class)` method which obtains a logger for a given class without making the class implement `Logging` interface.

Static logger API

---

gradle/wrapper/gradle-wrapper.properties
license-report.md
pom.xml
version.gradle

This PR releases the library to version `1.5.0`.
The most noticeable changes of the release are listed below.
* `Time.currentTime()` now returns the time with microsecond precision. The values are emulated, increasing for each consequent call (#504, #512).
* `(constraint_for)` is now supported by the Spine compiler (#505).
* Support for the new Column API has been added to the Spine compiler (#508).
* Logging API has been extended (#513).
For more details please navigate to the list of the closed pull requests and their descriptions.

Release 1.5.0

---

base/src/main/java/io/spine/json/Json.java
base/src/test/java/io/spine/json/JsonTest.java
license-report.md
pom.xml
version.gradle

While the Protobuf itself follows the ignorance strategy for unknown fields, we do want to follow the same strategy with JSON as well. 
Such an approach makes it easier to perform data migrations and allows overcome issues with parsing objects with older/newer proto schemas.

Ignore unknown fields in JSON parser

---

base/src/main/java/io/spine/validate/MessageValidator.java
base/src/main/java/io/spine/validate/option/PatternConstraint.java
base/src/main/proto/spine/options.proto
base/src/test/java/io/spine/validate/ValidationOfConstraintTest.java
base/src/test/java/io/spine/validate/option/PatternTest.java
base/src/test/proto/spine/test/validate/patterns.proto
gradle/wrapper/gradle-wrapper.properties
license-report.md
pom.xml
tools/model-compiler/src/main/java/io/spine/tools/gradle/compiler/ProtoModule.java
tools/plugin-base/src/test/java/io/spine/tools/gradle/SpinePluginBuilderTest.java
tools/smoke-tests/gradle/wrapper/gradle-wrapper.properties
tools/validation-generator/src/main/java/io/spine/tools/validate/ValidationCodeGenerator.java
version.gradle

In this PR we deprecate the `PatternOpntion.flags` field, which is an integer mask, in favour of the `modifiers` —  a new field which allows specifying regular expression modifiers in a descriptive manner.
Fixes [this issue](https://github.com/SpineEventEngine/core-java/issues/180).

Smarter regex modifiers

---

base/build.gradle
license-report.md
pom.xml
version.gradle

I've added publishing of `base` module protos as a separate artifact to ease integrations for programming languages that are not yet supported by the framework.

Publish base Protos as a separate artifact

---

.idea/misc.xml
base/src/main/java/io/spine/reflect/PackageGraph.java
license-report.md
pom.xml
tools/smoke-tests/annotator-tests/build.gradle
tools/smoke-tests/build.gradle
version.gradle

This PR advances the version to be able to build the `bootstrap` plugin (which requires all the dependencies to have the same version number).

Advance version to 1.5.8

---

base/src/main/proto/spine/options.proto
license-report.md
pom.xml
tools/protoc-plugin/README.md
tools/protoc-plugin/src/main/java/io/spine/tools/protoc/iface/InterfaceGenerator.java
tools/smoke-tests/model-compiler-tests/src/test/java/io/spine/tools/protoc/ProtocPluginTest.java
version.gradle

Consider options `(is)` and `(every_is)` applied to a type at the same time:
```proto
option (every_is).java_type = "Fruit";
message Tomato {
option (is).java_type = "Vegetable";
// ...
}
```
Currently, Java class `Tomato` only implements `Vegetable` interface.
With this PR we make `(is)` and `(every_is)` complementary. This way, Java class `Tomato` implements both `Vegetable` and `Fruit` interfaces.

Allow `(is)` & `(every_is)` simultaneously

---

base-validating-builders/buildSrc/build.gradle.kts
base-validating-builders/buildSrc/src/main/kotlin/io/spine/gradle/internal/CheckVersionIncrement.kt
base-validating-builders/buildSrc/src/main/kotlin/io/spine/gradle/internal/IncrementGuard.kt
base-validating-builders/buildSrc/src/main/kotlin/io/spine/gradle/internal/RunBuild.kt
base-validating-builders/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/io/spine/gradle/internal/CheckVersionIncrement.kt
buildSrc/src/main/kotlin/io/spine/gradle/internal/IncrementGuard.kt
buildSrc/src/main/kotlin/io/spine/gradle/internal/RunBuild.kt
buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
license-report.md
pom.xml
tools/proto-dart-plugin/src/main/java/io/spine/generate/dart/CachedDartProtocPlugin.java
tools/smoke-tests/buildSrc/build.gradle.kts
tools/smoke-tests/buildSrc/src/main/kotlin/io/spine/gradle/internal/CheckVersionIncrement.kt
tools/smoke-tests/buildSrc/src/main/kotlin/io/spine/gradle/internal/IncrementGuard.kt
tools/smoke-tests/buildSrc/src/main/kotlin/io/spine/gradle/internal/RunBuild.kt
tools/smoke-tests/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
version.gradle.kts

Recently, the Pub cache location on Windows has been [changed](https://github.com/dart-lang/pub/blob/82e60a3dcb3afe753563e7d304827fb650bc4833/lib/src/system_cache.dart#L38).
In this PR we bring our Gradle plugin for Dart projects up to the speed with the Pub tool.

Fix Pub cache location on Windows

---

base/src/main/java/io/spine/base/Environment.java
base/src/main/java/io/spine/base/EnvironmentType.java
base/src/main/java/io/spine/base/Production.java
base/src/main/java/io/spine/base/Tests.java
base/src/test/java/io/spine/base/EnvironmentTest.java
base/src/test/java/io/spine/base/environment/EnvironmentTest.java
base/src/test/java/io/spine/base/environment/Staging.java
base/src/test/java/io/spine/base/given/AppEngine.java
base/src/test/java/io/spine/base/given/AppEngineStandard.java
license-report.md
pom.xml
tools/model-compiler/src/main/java/io/spine/tools/compiler/gen/column/EntityWithColumnsSpec.java
version.gradle.kts

This PR simplifies `EnvironmentType` and `Environment`.
Now, allows to check for the class with `boolean is(Class<? extends EnvironmentType>), instead of `boolean is(EnvironmentType)`.
Now, no longer overrides `equals` and `hashCode` in suspicious ways. Instead, it simply acts as a stricter `interface` for a single `boolean enabled()` method.
Also, standard environment types are no longer singletons. We no longer encourage the extenders to be singletons as well.
Also resolves some Error Prone warnings.

`EnvironmentType` design tweaks

---

base-validating-builders/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
tools/proto-js-plugin/build.gradle.kts
tools/smoke-tests/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
version.gradle.kts

This PR prepares `base` for https://github.com/SpineEventEngine/config/pull/122.
It makes sure that the build yields no warnings.

Fail build on warning

---

.idea/misc.xml
base/src/main/java/io/spine/base/Environment.java
base/src/main/java/io/spine/base/EnvironmentType.java
base/src/main/java/io/spine/base/Production.java
base/src/main/java/io/spine/base/Tests.java
base/src/main/java/io/spine/base/TestsProperty.java
base/src/test/java/io/spine/base/EnvironmentTest.java
base/src/test/java/io/spine/base/environment/CustomEnvironmentTest.java
license-report.md
pom.xml
version.gradle.kts

This PR encapsulates work with the `io.spine.testging` system property and adds minor improvements for working with built-in `EnvironmentType`s. In particular:
* `Production` and `Tests` types are made singletons. We always had one copy of each anyway.
* Working with the system property `io.spine.testging` extracted into the class called `TestsProperty`.

Encapsulate `tests` property

---

base/src/main/java/io/spine/base/Time.java
base/src/test/java/io/spine/base/TimeTest.java
version.gradle.kts

If we run a spine-based project under the Java 11 platform we randomly may encounter the issue when `Time.currentTime()` returns an invalid timestamp.
The issue is that `Time` uses the `SystemTimeProvider` by default, which rely on the fact that `Instant.now()` returns time in millisecond precision, that was true for Java 8. The `SystemTimeProvider` emulates nanoseconds in order to split in time events that happened in the same millisecond, but if we have time with increased precision it leads us to the situation when the resulting amount of nanoseconds with emulation is bigger than allowed. This happens because starting from Java 9 `Instant.now()` may return time with increased precision if the underlying clock supports it. This issue also described in #553.
In this PR I made the …

Truncate time to milliseconds

---

version.gradle.kts

This PR changes the `version.gradle.kts` file to adhere to the contract of the [publishing application](https://github.com/SpineEventEngine/publishing.)

Structure the version file

---

.idea/misc.xml
license-report.md
pom.xml
version.gradle.kts

This PR does the release of a library version `1.6.0`.
This release brings numerous API improvements, as well as fixes and infrastructure updates to the framework.
1. Custom environments support is introduced [#539, #542, #545]. 
The `Environment` now exposes API to register user-defined environment types.
This can be done by extending the `EnvironmentType` class:
```java
public final class AwsLambda extends EnvironmentType {
@Override
public boolean enabled() {
// ...
}
}
```
Then, the environment can be registered to give the user ability to check if it's active at any given moment of time:
```java
Environment.instance()
.register(new AwsLambda());
// ...
if (Environment.instance().is(AwsLambda.class)) {
this.sender = new AwsEmailSender();
}
```
 The Spine framework provides two …

Release `1.6.0`

---

version.gradle.kts

This PR updates the configuration files, so that the modules of this repository are published from `2.x-jdk8-master` branch.
The version of the modules has been set to `2.0.0-jdk8-SNAPSHOT.4`.

[2.x-jdk8] Enable publishing

---

license-report.md
pom.xml
version.gradle.kts

Right now, the `2.x` snapshots are published to the release repo.
In order to fix that, this changeset incorporates the most [recent changes](https://github.com/SpineEventEngine/config/pull/144) to the `config`. Once these are merged, the artifacts will hopefully be published to the repository designed for snapshots.

[2.x-jdk8] Publish snapshots properly

---

tools/tool-base/src/main/java/io/spine/code/gen/java/column/ColumnContainerSpec.java
version.gradle.kts

Previously, we were generating a piece of code into the Java class of an Entity state, and we were doing it like this:
```java
...  // column `definitions()` method:
HashSet result = new HashSet<>();
...
```
However, this expression uses a raw `HashSet` type type instead of a parameterized one. It results in Checkstyle failures in the projects in which the code-generated Entity states are used.
Therefore, this changeset updates the generation routines to produce the piece as follows.
```java
...
HashSet<EntityColumn<EntityStateType, ?>> result = new HashSet<>();
...
```
The snapshot counter in the version has been increased by one to `SNAPSHOT.6`.

[2.x-jdk8] Remove a warning in the generated code of Entity state

---

license-report.md
pom.xml
tools/tool-base/src/main/java/io/spine/code/fs/DirectoryReference.java
tools/tool-base/src/main/java/io/spine/code/fs/FileReference.java
tools/tool-base/src/test/java/io/spine/code/fs/js/FileReferenceTest.java
version.gradle.kts

This PR fixes a crash in `FileReference.directory()`. Currently, the method throws an exception if the file reference has no directory, i.e. it's a simple file name (possibly, with the "`./`" prefix). This PR fixes that crash.

Allow short relative paths in imports

---

license-report.md
pom.xml
pull
version.gradle.kts

This changeset updates the `pull` script in the root of this repository so that it switches the `config` to its `master` branch.
As there is another `2.x-jdk8-master` branch in this repo, this change is a precautionary measure for those working with both framework versions.

Ensure that `base/master` always looks at `config/master` branch

---

base/src/test/java/io/spine/type/TypeUrlTest.java
base/src/test/proto/spine/test/type/no_prefix.proto
license-report.md
pom.xml
testlib/build.gradle.kts
tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/ExtensionTest.java
version.gradle.kts

This PR addresses #264 allowing type URLs with empty type prefix. 
We cannot demand having the prefix because this feature is not fully developed in the Protobuf. We do use the prefix to distinguish our types and types of the apps based on Spine from Google API types. But it goes no further. Therefore, users may not want to use this prefix feature because it does not make sense for them.
As a bonus feature, this PR eliminates the dependency on Hamchrest and removes it from the Testlib API.

`TypeUrl` without type prefix

---

.idea/codeStyles/Project.xml
.idea/misc.xml
base/src/main/java/io/spine/string/Diags.java
base/src/test/java/io/spine/string/DiagsTest.java
version.gradle.kts

This PR starts addressing #590, providing `Collector`s for popular cases of enumerating objects in diagnostic messages.

Add collectors for diagnostic messages

---

.idea/inspectionProfiles/Project_Default.xml
base/src/main/java/io/spine/io/Resource.java
base/src/main/java/io/spine/validate/Validate.java
base/src/test/java/io/spine/validate/ValidateTest.java
license-report.md
pom.xml
testlib/src/main/java/io/spine/testing/UtilityClassTest.java
version.gradle.kts

This PR removes deprecated API.
Please mention these changes in [v1.7 release notes](https://github.com/SpineEventEngine/core-java/issues/1337).

Remove deprecated API

---

license-report.md
pom.xml
tools/proto-dart-plugin/src/main/java/io/spine/dart/PubCache.java
tools/proto-dart-plugin/src/test/java/io/spine/dart/PubCacheTest.java
version.gradle.kts

This PR allows our Dart-related tools to work with custom Pub cache location on Windows.
Previously, the only place we were looking for the cache by default was the `%LOCALAPPDATA%` dir. Some versions of Pub use `%APPDATA%` dir instead. Now we support both without extra configuration.

Fix Pub cache on Windows

---

base-validating-builders/build.gradle.kts
base-validating-builders/buildSrc/build.gradle.kts
base-validating-builders/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
license-report.md
pom.xml
tests/build.gradle.kts
tests/buildSrc/build.gradle.kts
tests/buildSrc/src/main/kotlin/io/spine/gradle/internal/deps.kt
tools/javadoc-prettifier/src/test/resources/build.gradle.kts
tools/model-compiler/src/test/java/io/spine/tools/gradle/compiler/given/Project.java
tools/model-compiler/src/test/resources/build.gradle.kts
tools/proto-js-plugin/src/test/resources/build.gradle.kts
version.gradle.kts

We're phasing out the usage of the JCenter Maven repository, replacing it with the conventional Maven Central. JCenter is announced to be shut down soon and is already experiencing deteriorated performance.

Phase out `jcenter()`

---

.github/workflows/build.yml
.github/workflows/publish.yml
base/build.gradle.kts
license-report.md
pom.xml
version.gradle.kts

In this PR we:
- remove Java types generated from Google Protobuf from the `base` artifacts;
- fix validation code generation for `base` types;
- fix the JaCoCo report generation (from a `config` script).

Fix coverage reports and artifacts

---

base/src/main/java/io/spine/protobuf/Durations2.java
base/src/test/java/io/spine/string/Durations2Test.java
license-report.md
pom.xml
version.gradle.kts

This PR deprecates some of the `Duration2`  utilities that are already available from `com.google.protobuf.Durations`.

Deprecate duplicating `Duration2` utils

---

license-report.md
pom.xml
tools/plugin-testlib/src/main/java/io/spine/tools/gradle/testing/GradleProject.java
tools/plugin-testlib/src/main/java/io/spine/tools/gradle/testing/TaskArguments.java
tools/plugin-testlib/src/test/java/io/spine/tools/gradle/testing/TaskArgumentsTest.java
version.gradle.kts

In this PR we allow passing environment variables to a `GradleProject` and fix the formatting of Gradle properties in `TaskArguments`.

Configure environment in `GradleProject`

---

version.gradle.kts

This PR fixes the failed [publishing run](https://github.com/SpineEventEngine/base/actions/runs/961181129).

Fix publishing

---

.github/workflows/publish.yml
build.gradle.kts
license-report.md
pom.xml
version.gradle.kts

in this PR we disable the Google Cloud Artifact Registry Maven repo publishing.
It has proven to be faulty with big artifacts (e.g. fat JARs).  We suspect that the problem has to do with the lifespan of the access token, issued by Google with the help of the Gradle plugin (which we use as a library — `com.google.cloud.artifactregistry`).
[This change](https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools/pull/53) ought to fix the issue, once it is released. Meanwhile, we simply skip the GCAR Maven repo.
Once the mentioned change is applied, we should update our dependencies and check again. To enable publishing, simply restore the commented YAML code in `.github/workflows/publish.yml`.

Isolate GCAR publishing

---

version.gradle.kts

This PR only bumps version from *.50 to *.51 to trigger publishing failed during [this workflow](https://github.com/SpineEventEngine/base/actions/runs/1184388682).
The reason for failed version increment check will be investigated shortly by @armiol.

Bump version

---

.travis.yml
buildSrc/src/main/kotlin/io/spine/internal/gradle/CheckVersionIncrement.kt
license-report.md
pom.xml
tests/buildSrc/src/main/kotlin/io/spine/internal/gradle/CheckVersionIncrement.kt
version.gradle.kts

Previously, upon each successful build we attempted to update all repositories dependant onto `base` artifacts. In particular, we wanted to increment their version and put a freshly built dependency onto `base` libs into their dependencies.
However, this mechanism does not work properly. Therefore, PR switches it off.

Do not trigger the updates of dependant repositories

---

base/src/main/proto/spine/options.proto
buildSrc/build.gradle.kts
buildSrc/src/main/groovy/license-report-project.gradle
buildSrc/src/main/kotlin/io/spine/internal/gradle/Clean.kt
license-report.md
pom.xml
settings.gradle.kts
tests/buildSrc/build.gradle.kts
tests/buildSrc/src/main/groovy/license-report-project.gradle
tests/buildSrc/src/main/kotlin/io/spine/internal/gradle/Clean.kt
version.gradle.kts

In this PR we introduce the `compare_by` option. It allows users to specify the natural ordering strategy for messages, based on the values of their fields.
Example:
```proto
message LocalDate {
option (compare_by) = {
field: "year" field: "month" field: "day"
};
int32 year = 1;
Month month = 2;
uint32 day = 3;
}
```
Such declaration indicates that the value must be compared by the fields `year`, `month`, and `day` in that order.
Recursive comparisons are also supported:
```proto
message LocalDateTime {
option (compare_by) = {
field: "date" field: "time"
};
LocalDate date = 1;
LocalTime time = 2;
}
```
Here, both `LocalDate` and `LocalTime` must be marked with the `(compare_by)` option as well as `LocalDateTime`. 
This feature is applicable to any Protobuf message.
**Note.** This PR …

Comparable messages

---

.github/workflows/publish.yml
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt
license-report.md
pom.xml
tests/buildSrc/build.gradle.kts
tests/buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt
version.gradle.kts

In this PR we enable publishing artifacts to the Google Cloud Artifact Registry.
Previously, there was an issue with uploading large artifacts. It seems to be gone now.
The version is bumped to `2.0.0-SNAPSHOT.55`, since `SNAPSHOT.54` was "eaten up" while testing the publishing on CI.

Return of the GCAR

---

.github/workflows/detekt-analysis.yml
buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/VersionWriter.kt
tests/buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
tests/buildSrc/src/main/kotlin/io/spine/internal/gradle/VersionWriter.kt
version.gradle.kts

This PR adds workflow for static analysis of Kotlin code [using Detekt](https://github.com/SpineEventEngine/config/issues/227).

Enable Kotlin static code analysis

---

buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/UpdateGitHubPages.kt
license-report.md
pom.xml
tests/buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/UpdateGitHubPages.kt
version.gradle.kts

This changeset switches `base` to a [smarter version of `UpdateGitHubPages`](https://github.com/SpineEventEngine/config/pull/266) to fix own publishing.
The version is increased to be `2.0.0-SNAPSHOT.64`.

Grab the smarter version of `UpdateGitHubPages`

---

base/src/main/java/io/spine/util/Preconditions2.java
buildSrc/src/main/groovy/license-report-repo.gradle
license-report.md
pom.xml
tests/buildSrc/src/main/groovy/license-report-repo.gradle
version.gradle.kts

This changeset adds the missing `@CanIgnoreReturnValue` to `Preconditions2` API.
The version is set to `2.0.0-SNAPSHOT.65`.

Add missing `@CanIgnoreReturnValue`

---

base/src/main/java/io/spine/validate/option/GoesConstraint.java
base/src/main/java/io/spine/validate/option/MaxConstraint.java
base/src/main/java/io/spine/validate/option/MinConstraint.java
base/src/main/java/io/spine/validate/option/PatternConstraint.java
base/src/main/java/io/spine/validate/option/RequiredConstraint.java
base/src/main/java/io/spine/validate/option/ValidateConstraint.java
base/src/main/proto/spine/options.proto
base/src/test/java/io/spine/validate/ErrorMessageTest.java
base/src/test/java/io/spine/validate/option/PatternTest.java
buildSrc/src/main/groovy/slow-tests.gradle
buildSrc/src/main/groovy/test-artifacts.gradle
buildSrc/src/main/groovy/test-output.gradle
buildSrc/src/main/kotlin/io/spine/internal/dependency/ErrorProne.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/report/coverage/JacocoConfig.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/testing/Artifacts.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/testing/Logging.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/testing/Tasks.kt
license-report.md
pom.xml
version.gradle.kts

As a part of the validation library renovation, we change the format of error messages presented with the constraint violations.
This means replacing the `%s` placeholders with case-specific tokens such as `{value}` and `{other}`.
We also deprecate the old `msg_format` fields and replace them with `error_msg` in order not to confuse the users with the word "format".

Document validation error message format in `options.proto`

---

.idea/inspectionProfiles/Project_Default.xml
base/build.gradle.kts
base/src/main/java/io/spine/code/fs/FsObject.java
build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/io/spine/internal/dependency/Jackson.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt
gradle/wrapper/gradle-wrapper.properties
license-report.md
pom.xml
version.gradle.kts

This PR:
* Deprecates the `FsObject.directory()` method which turned to have a confusing name. The `parent()` method was introduced instead.
* Removes redundant settings in the build scripts.
* Bumps `config`.

Deprecate `FsObject.directory()` method

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
license-report.md
pom.xml
version.gradle.kts

This PR updates Protobuf dependency to the version `3.19.2`.

Bump Protobuf

---

base/src/main/kotlin/io/spine/io/Glob.kt
base/src/test/kotlin/io/spine/io/GlobTest.kt
license-report.md
pom.xml
version.gradle.kts

This PR extends the `Glob` class to allow having more than one file extension per instance (using the `**.{ext1,ext2}` syntax. 
Also the class got the `extensionLowerAndUpper()` method which allows having both lower- and uppercase versions of extensions for handling unusual cases of seasoned source code files coming with uppercase names.

Allow more than one extension per `Glob`

---

base/src/main/kotlin/io/spine/io/Glob.kt
base/src/test/java/io/spine/io/GlobTest.java
license-report.md
pom.xml
version.gradle.kts

This PR improves the `Glob` class in the following ways:
* Adds overload method accepting `Iterable<String>` parameters.
* Makes methods accept `String` instead of `CharSequence`. Working with `CharSequence` was a bit awkward in the implementation, and when using from Java too.

Improve `Glob` API

---

base/src/main/java/io/spine/environment/Environment.java
buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/CheckVersionIncrement.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/IncrementGuard.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/PublishExtension.kt
buildSrc/src/main/kotlin/pmd-settings.gradle.kts
license-report.md
pom.xml
version.gradle.kts

It used to be `INFO`, but it's not very informative and is a bit noisy. This PR demotes it to the `_debug()` level, which is just `FINE`.

Demote debug level for diag. messages when switching `Environment` type

---

build.gradle.kts
license-report.md
pom.xml
version.gradle.kts

This PR removes tasks for generating multi-module documentation by Dokka. It is done by moving the application of `dokka-for-java` plugin from `allprojects{}` to `subprojects{}` block. The reasons behind these changes are the following:
- we do not need this functionality;
- custom `dokka-for-java` plugin does not configure multi-module Dokka tasks.

Remove Dokka multimodule functionality

---

base/src/main/java/io/spine/annotation/Internal.java
base/src/main/java/io/spine/query/AbstractQueryBuilder.java
base/src/main/java/io/spine/type/UnexpectedTypeException.java
base/src/main/java/io/spine/type/UnpublishedLanguageException.java
base/src/main/kotlin/io/spine/type/MessageExtensions.kt
base/src/main/proto/spine/options.proto
base/src/test/java/io/spine/type/UnknownTypeExceptionTest.java
base/src/test/java/io/spine/type/UnpublishedLanguageExceptionTest.java
license-report.md
pom.xml
testlib/src/main/java/io/spine/testing/StubMessage.java
testlib/src/test/java/io/spine/testing/StubMessageTest.java
version.gradle.kts

This PR continues extending usage of `internal_type` proto option and `@Internal` Java annotation for marking non-published language of a bounded context.
* Documentation of the `@Internal` annotation was updated accordingly.
* The retention policy of the annotation was changed from `SOURCE` to `RUNTIME` because we're going to check it then.
* `UnpublishedLanguageException` was introduced to be thrown when the user attempts to use a non-published message outside of the context.
* Several Kotlin-based extensions for `Message` types and utility functions related to published language were introduced.
* `StubMessage` class was introduced to simplify creation of stub message types in tests.

More on unpulished language

---

base/src/main/java/io/spine/reflect/GenericTypeIndex.java
base/src/test/java/io/spine/reflect/GenericTypeIndexTest.java
base/src/test/java/io/spine/reflect/TypesTest.java
license-report.md
pom.xml
version.gradle.kts

This PR:
* Fixes Javadoc of `GenericTypeIndex` which previously misused the word `extends` where `implements` should be said.
* Extends the Javadoc with the code example of using enum members for obtaining generic type arguments.
* Fixes the placement of `Types` utility class.
* Adds test for enum-based type access.

Fix Javadoc and tests for `GenericTypeIndex`

---

base/src/main/java/io/spine/type/UnpublishedLanguageException.java
license-report.md
pom.xml
version.gradle.kts

This PR makes the constructor of `UnpublishedLanguageException` accepting a type name `public` so that users of the class don't have to create default instances of a message (knowing the type) just to create an exception.

Open a constructor of `UnpublishedLanguageException` which accepts a type name

---

base/src/main/java/io/spine/validate/Validate.java
base/src/test/kotlin/io/spine/validate/MessageExtensionsTest.kt
license-report.md
pom.xml
version.gradle.kts

This PR addresses the issue #60 and adds Kotlin extension for validating `Message` instance.

Improve validation checks

---

base/src/main/java/io/spine/validate/Validate.java
base/src/main/java/io/spine/validate/ValidatingBuilder.java
base/src/main/kotlin/io/spine/validate/MessageExtensions.kt
license-report.md
pom.xml
version.gradle.kts

This PR restores the `Validate.checkValid()` method returning `void` (to fix the broken API) and deprecates it in favor of the one returning the passed message.

Fix validation check

---

gradle/wrapper/gradle-wrapper.properties
license-report.md
pom.xml
version.gradle.kts

To overcome `StackOverflow` when publishing.

Bump Gradle to 7.6 Nightly

---

base/src/main/java/io/spine/util/Text.java
base/src/test/kotlin/io/spine/util/TextTest.kt
license-report.md
pom.xml
version.gradle.kts

This PR fixes the missing check that was announced in Javadoc, but wasn't implemented in the past PR which introduced the `Text` utility.

Fix missing check for no separators in text lines

---

base/src/main/java/io/spine/util/Text.java
base/src/test/kotlin/io/spine/util/TextTest.kt
license-report.md
pom.xml
version.gradle.kts

This PR teaches the `Text` class to remember its value so that users do not have to merge lines to work with the text as a whole thing.

Remember `Text` value

---

.idea/misc.xml
build.gradle.kts
buildSrc/src/main/kotlin/deps-between-tasks.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Pmd.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/fs/LazyTempPath.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/RepositoryExtensions.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/github/pages/Update.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/protobuf/ProtoTaskExtensions.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Artifacts.kt
license-report.md
pom.xml
testlib/src/main/java/io/spine/testing/logging/mute/package-info.java
version.gradle.kts

This PR adds Kotlin code generation for proto types.  It also updates `ProtoTaskExtensions.kt` for adding file-wide suppression of deprecations to the generated Kotlin code.
The Protobuf version was rolled back because `3.21.7` does not add visibility modifiers to the generated code. See my comments for this PR for the details on the issue.

Add Kotlin code generation

---

.github/workflows/build-on-ubuntu.yml
.github/workflows/build-on-windows.yml
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/deps-between-tasks.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Pmd.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/testing/Tasks.kt
license-report.md
pom.xml
testlib/src/main/kotlin/io/spine/testing/TruthExtensions.kt
testlib/src/test/kotlin/io/spine/testing/TruthExtensionsSpec.kt
version.gradle.kts

This PR provides Kotlin DSL for `StringSubject`, `IterableSubject`, `OptionalSubject`, and `ProtoSubject`.

Add Kotlin extension functions for selected Truth subjects

---

base/src/main/java/io/spine/string/Quoter.java
base/src/main/kotlin/io/spine/string/Strings.kt
base/src/main/kotlin/io/spine/util/MoreCollections.kt
base/src/main/proto/spine/options.proto
base/src/test/kotlin/io/spine/string/StringsSpec.kt
base/src/test/kotlin/io/spine/util/MoreCollectionsSpec.kt
license-report.md
pom.xml
version.gradle.kts

This PR:
* Adds `VIEW` alias for `PROJECTION` in the `Enum.Kind` enumeration. This is to allow writing `option (entity.kind)=VIEW` which plays nicer with `View` types in ProtoData (which is hopefully would be added to `core-java` soon).
* Moves general purpose Kotlin extensions from ProtoData.

More Kotlin extensions

---

base/src/main/java/io/spine/util/Preconditions2.java
license-report.md
pom.xml
version.gradle.kts

This changeset updates the public API of `Preconditions2` with `@CanIgnoreReturnValue` annotation, where applicable.
Addresses #734.

[1.x] @CanIgnoreReturnValue to  `Preconditions2`

---

license-report.md
pom.xml
testlib/src/main/kotlin/io/spine/testing/GuavaExtensions.kt
testlib/src/main/kotlin/io/spine/testing/TruthExtensions.kt
version.gradle.kts

This PR:
* Adds block function for `NullPointerTester`.
* Consolidates all extensions for this class under `GuavaExtensions.kt` for better visibility.

Extensions for `NullPointerTester`

---

.github/workflows/publish-v1.yml
license-report.md
pom.xml
version.gradle.kts

In this PR, the automatic update of GH Pages content is switched off for v1 branches.
The idea is that GH Pages update replaces the documentation currently residing there. While this is helpful, we don't want it happening automatically, as as of time of update, the documentation of 2.x may be already displayed as "current".
The publishing of the documentation from v1 branch should be executed manually using [Publish Documentation](https://github.com/SpineEventEngine/config/tree/master/scripts/publish-documentation) scripts instead.

[1.x] Publishing without GH Pages update

---

.github/workflows/publish-v1.yml

This PR attempts to re-publish the artifacts with the Validating Builders assembled properly.
Also, the latest `config/1.x` now allows to properly detect whether the published artifact is a snapshot.

[1.x] Publishing with Validating Builders

---

base/build.gradle.kts
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
license-report.md
pom.xml
version.gradle.kts

This PR removes the unnecessary configuration of Java source sets, which caused duplicated input for the `sourcesJar` task, which in turns [failed publishing](https://github.com/SpineEventEngine/base/actions/runs/3541486560).

Fix duplicated input for `sourcesJar` task

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
license-report.md
pom.xml
version.gradle.kts

This PR updates `Spine` dependency to set latest versions of the internal dependencies.
Most of dependencies declared in the `Spine` object are not used by `base` (because of the nature of this project).The aim of this PR is to be the reference point of propagation of these version information in addition to `config`, which will be updated following resolution of this PR.

Bump internal dependencies

---

base/build.gradle.kts
buildSrc/src/main/kotlin/BuildExtensions.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/JUnit.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Artifacts.kt
license-report.md
pom.xml
version.gradle.kts

This PR:
1. Documents the usage of `protobuf` dependency in the `base` module.
2. Updates dependencies from the latest `config`.

Document `protobuf` dependency

---

base/src/main/kotlin/io/spine/string/Indent.kt
base/src/main/kotlin/io/spine/string/Separator.kt
base/src/main/kotlin/io/spine/string/Strings.kt
base/src/test/kotlin/io/spine/string/IndentSpec.kt
base/src/test/kotlin/io/spine/string/StringsSpec.kt
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/javadoc/JavadocConfig.kt
license-report.md
pom.xml
version.gradle.kts

This PR:
* Adds extensions functions for `String` which work similarly to `trimIndent()` and `prependIndent()` from Kotlin, but unlike them preserve system line separators.
* Add the `Indent` class for working with indentation. The new class is going to replace its Java namesake from `tool-base`.

Preserving system line separators

---

base/src/main/java/io/spine/environment/OsFamily.java
base/src/test/kotlin/io/spine/environment/OsFamilySpec.kt
license-report.md
pom.xml
version.gradle.kts

This PR brings `OsFamily` enum which was a part of `tool-base` into this code tree. The ability to detect current OS is needed only for tools, but for libraries that may need to deal with system specifics. For example, tests of the Text library already need to be able current OS because line separators are OS-specific.
It is expected that `tool-base` would migrate to `OsFamily` becauses it fixes an issue with detecting Unix (non-macOS) systems.

Detection of OS family

---

base/src/main/java/io/spine/type/ApiOption.java
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/io/spine/internal/dependency/Grpc.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Artifacts.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/ProtoExts.kt
gradle/wrapper/gradle-wrapper.properties
license-report.md
pom.xml
testlib/src/test/kotlin/io/spine/protobuf/GoogleTypesTest.kt
version.gradle.kts

This PR bumps:
* Protobuf -> [`3.22.0`](https://github.com/protocolbuffers/protobuf/releases/tag/v22.0).  There are many improvements related to code generation for for Java and Kotlin.
* Protobuf Gradle Plugin -> [`0.9.2`](https://github.com/google/protobuf-gradle-plugin/releases/tag/v0.9.2).
* Removes `compiler/plugin.proto` from the list of standard files available in descriptors bundled with `spine-base` because `protobuf-java` no longer contains this file in the distribution. Please see the comment in `GoogleTypesTest.kt` for details.

Bump Protobuf, its plugin and other dependencies

---

base/src/test/kotlin/io/spine/value/ValueHolderSpec.kt
license-report.md
pom.xml
testlib/src/test/kotlin/io/spine/protobuf/GoogleTypesTest.kt
version.gradle.kts

This PR adds test for `ValueHolder.value()` not being final. This is needed because some descendants in `core-java` override this method for casting return type values.
Also, it fixes the type [reported](https://github.com/SpineEventEngine/base/pull/780#pullrequestreview-1314716328) for the previous PR.

Test overriding of `ValueHolder.value()` method

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotest.kt
license-report.md
pom.xml
version.gradle.kts

This PR bumps Kotest to the lucky version number.

Bump Kotest -> `5.5.5`

---

build.gradle.kts
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
license-report.md
pom.xml
src/test/kotlin/io/spine/LoggingSmokeTest.kt
version.gradle.kts

This PR adds a smoke test for `spine-logging` to make sure that the logging is working in concrete modules. 
`base` module is the first one where this test is added. Further, it will be added to more modules. 
`Spine` dependency object will also be updated in `config` when this PR is approved.

Add a smoke test for `spine-logging

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
license-report.md
pom.xml
src/main/java/io/spine/code/proto/FileDescriptors.java
src/main/java/io/spine/code/proto/FileSet.java
src/main/java/io/spine/code/proto/Linker.java
src/main/java/io/spine/io/Delete.java
src/main/java/io/spine/type/KnownTypes.java
version.gradle.kts

This PR updates the version of Spine Logging, migrating statically initialized loggers to use `LoggingFactory.forEnclosingClass()`.

Detect logging class

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
dependencies.md
pom.xml
src/main/java/io/spine/annotation/Internal.java
src/main/kotlin/io/spine/string/Separator.kt
src/main/kotlin/io/spine/string/Strings.kt
src/test/kotlin/io/spine/string/StringsSpec.kt
version.gradle.kts

This PR extends the collection of extension functions for working with `String` and line endings.
Addressed issues: #808 and #809.
Other notable changes:
* The documentation for the `Internal` annotate was rewritten using AI assistance, making it easier to read, and avoiding excessive markup.
* Protobuf was bumped to `3.25.1`.

Extend string utils

---

build.gradle.kts
buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/io/spine/internal/dependency/IntelliJ.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Kotlin.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/KotlinX.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/Repositories.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/protobuf/ProtoTaskExtensions.kt
dependencies.md
pom.xml
src/main/resources/desc.ref
src/test/resources/desc.ref
version.gradle.kts

This changeset addresses the inconsistencies in descriptor set generation.
Now, this library is going to have a descriptor file named after `base`'s Maven coordinates. Also, the manually placed `desc.ref` files were removed from the sources, as they are now generated automatically. See [config#504](https://github.com/SpineEventEngine/config/pull/504) for more details.
Lastly, the latest dependencies from `config` were picked up.

Improve generation of descriptor set files 

---

buildSrc/src/main/kotlin/DokkaExts.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Validation.kt
dependencies.md
pom.xml
src/main/java/io/spine/annotation/Beta.java
src/main/java/io/spine/annotation/Experimental.java
src/main/java/io/spine/annotation/SPI.java
src/main/java/io/spine/code/java/ClassName.java
src/main/proto/spine/options.proto
src/test/kotlin/io/spine/annotation/AnnotationsSpec.kt
version.gradle.kts

This PR sets `RUNTIME` retention policy for API level annotation classes. 
Before this PR `RUNTIME` retention was only assigned for `Internal`. Now we make all the API level annotations to have this retention to ease the usage in tests related to code generation.
Other notable changes:
* Fixed creation of `ClassName` for a service descriptor in a file with `java_multiple_files = false`. Previously, it gave a nested class name. In fact, gRPC stubs are always top-level classes.

`RUNTIME` retention for API level annotations

---

buildSrc/src/main/kotlin/io/spine/internal/dependency/Protobuf.kt
dependencies.md
pom.xml
src/main/kotlin/io/spine/io/Closeable.kt
src/test/kotlin/io/spine/io/CloseableSpec.kt
version.gradle.kts

This PR brings the `Closeable` interface which was for years a part of `core-java` on the server side to Spine Base. 
Recent works on code generation in `tool-base` show that we need a custom `Closeable` in modules that do not have `io.spine.server` package in their classpath (and we don't want to bring the dependency on `spine-server` artifact just because of the interface).
It is also expected that the interface would be useful for other usage scenarios that do not assume dependency on `spine-server`.
After copying the interface was converted to Kotlin and supplied with unit tests.
* Protobuf -> `3.25.2`

Promote `Closeable` inteface from `io.spine.server`

---

buildSrc/build.gradle.kts
dependencies.md
pom.xml
src/main/java/io/spine/annotation/Modified.java
src/test/java/io/spine/annotation/ModifiedSpec.java
version.gradle.kts

This PR introduces the `Modified` annotation type which is needed for the cases when Spine tools update the code generated by other tools. 
We need to tell who did the modifications because the changes ProtoData and Model Compilers apply are significant.
We also may want to modify the Protobuf generated code even further. So, relevant attributions are appropriate and wanted.

`Modified` annotation

---

buildSrc/build.gradle.kts
buildSrc/src/main/kotlin/Repositories.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Coroutines.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/GrpcKotlin.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/IntelliJ.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Jackson.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/Publications.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/publish/SpinePublishing.kt
buildSrc/src/main/kotlin/write-manifest.gradle.kts
dependencies.md
pom.xml
src/main/kotlin/io/spine/io/Paths.kt
src/main/kotlin/io/spine/string/Strings.kt
src/test/kotlin/io/spine/io/PathsSpec.kt
src/test/kotlin/io/spine/string/StringsSpec.kt
version.gradle.kts

This PR adds extensions for `String` and `Path` that were previously adopted when advancing McJava. Since these extensions are generic enough, we bring them to the `base` project.
`config` was also updated.

Bring extensions for `Base64` encoding from McJava

---

.github/workflows/build-on-ubuntu.yml
dependencies.md
pom.xml
version.gradle.kts

This changeset updates the Ubuntu build to submit the coverage reports properly.
See [config#515](https://github.com/SpineEventEngine/config/pull/515) for more information.

Use the latest version of Codecov GitHub Actions — `v4`

---

buildSrc/src/main/kotlin/jvm-module.gradle.kts
dependencies.md
pom.xml
src/main/kotlin/io/spine/io/Paths.kt
src/main/kotlin/io/spine/string/Strings.kt
src/test/kotlin/io/spine/io/PathsSpec.kt
src/test/kotlin/io/spine/string/StringsSpec.kt
version.gradle.kts

This PR adds the aforementioned extensions for later usage, in particular, in ProtoData and McJava for "gymnastics" files with different formats.

Add extensions `String.ensurePrefix(String)` and `Path.replaceExtension(String)`

---

.idea/.name
.idea/codeStyles/Project.xml
build.gradle.kts
dependencies.md
pom.xml
src/main/kotlin/io/spine/compare/ComparatorProvider.kt
src/main/kotlin/io/spine/compare/ComparatorRegistry.kt
src/main/kotlin/io/spine/compare/ProtoComparators.kt
src/main/kotlin/io/spine/compare/ProtoWellKnownComparators.kt
src/test/kotlin/io/spine/compare/ComparatorRegistrySpec.kt
version.gradle.kts

This PR introduces the `ComparatorRegistry` for maintaining `T::class -> Comparator<T>` mapping of available comparators. New comparators can be registered using the `ComparatorProvider` service provider.
We are going to use this registry when generating Java code for handling `compare_by` option in Proto messages. 
Please note, the registry along **with its custom providers** should be present in both generation and generated message's runtimes. The registry usage is incorporated into the generated code only if we are sure that it has the appropriate comparator, which is checked during the code generation.

Implement `ComparatorRegistry`

---

.idea/inspectionProfiles/Project_Default.xml
dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR introduces a separate `EveryIsOption` type for the `(every_is)` file option. Previously the file option and the message option `(is)` were served by the same type called `IsOption`.
During the reimplementation of the code generation process in McJava it was decided that the `generate` flag of `IsOption` does not make sense for `(is)` option because it would produce a marker interface for only one message class.
So, this PR renames the existing `IsOption`  into `EveryIsOption` and introduces new `IsOption` type which does not have the `generate` flag.
* The `constraint_for` message option was deprecated because new Validation library does not support this mechanism which turned to be really hard to use.

Have separate types for `every_is` and `is` options

---

dependencies.md
pom.xml
src/main/kotlin/io/spine/string/CharSequenceExts.kt
src/test/kotlin/io/spine/string/CharSequenceExtsSpec.kt
version.gradle.kts

This PR adds `CharSequence.containsAny()` extension function so that it's easier to detect several prohibited characters.

Add `CharSequence.containsAny()` extension function

---

dependencies.md
pom.xml
src/main/kotlin/io/spine/compare/ComparatorRegistry.kt
version.gradle.kts

This PR makes `ComparatorRegistry` provide static methods for Java callers.
So that, `ComparatorRegistry.INSTANCE.get()` becomes `ComparatorRegistry.get()`.

Provide static methods for `ComparatorRegistry`

---

.idea/codeStyles/Project.xml
.idea/inspectionProfiles/Project_Default.xml
buildSrc/src/main/kotlin/BuildExtensions.kt
buildSrc/src/main/kotlin/DependencyResolution.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/GradleDoctor.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/McJava.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/ProtoData.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Roaster.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Spine.kt
buildSrc/src/main/kotlin/io/spine/internal/dependency/Validation.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/dokka/DokkaExtensions.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/dokka/TaskContainerExtensions.kt
buildSrc/src/main/kotlin/io/spine/internal/gradle/report/license/MarkdownReportRenderer.kt
buildSrc/src/main/kotlin/jacoco-kotlin-jvm.gradle.kts
dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR fixes the syntax of using message-based option initialisation in `options.proto`. Also some minor touches to the text layout in this file were also made.
* `buildSrc` was updated from `config`.

Fix proto option example

---

dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR mentions the ability to pass external messages to `(compare_by)` option using a custom comparator.

Actualize docs to `(compare_by)` option

---

.idea/inspectionProfiles/Project_Default.xml
dependencies.md
pom.xml
src/main/java/io/spine/base/Field.java
src/main/java/io/spine/base/Identifier.java
src/main/java/io/spine/protobuf/AnyPacker.java
src/main/java/io/spine/type/EnumType.java
src/main/java/io/spine/type/MessageType.java
src/main/java/io/spine/type/ServiceType.java
src/main/java/io/spine/type/TypeUrl.java
src/test/java/io/spine/type/TypeUrlTest.java
src/test/kotlin/io/spine/type/KnownTypesSpec.kt
version.gradle.kts

This PR introduces static factory method for `TypeUrl` via `GenericDescriptor`. Previously, we had factories accepting `Descriptor`, `EnumDescriptor`, and `ServiceDescriptor`. But in fact `GenericDescriptor` has everything we need for creating `TypeUrl`.
Corresponding static factories named `from()` were deprecated.

Create `TypeUrl` via `GenericDescriptor`

---

dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR adds more details to `(set_once)` option specification.

Update docs to `(set_once)` option

---

dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR updates specs to `(goes)` option. 
In particular, it specifies the supported field types and replaces `%s`-based error message pattern for named placeholders, just as in `IfSetAgain` option.

Update specs to `(goes)` option

---

dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR unifies error messages format for all Spine options. Previously, the default error messages used `printf`-style format, but the custom ones expected placeholders instead. Now, both the custom and the default messages expect a string, which may contain placeholders in an arbitrary order.
A number of placeholders have been increased to allow specifying more detailed errors.

Use named placeholder for error messages in `options.proto`

---

dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR assigns a new field number to the field, which has changed the type in #842. 
Not following this convention, breaks compilation of ProtoData with `InvalidWireTypeException`. 
I've tested the local publication. ProtoData builds successfully with this change.

Properly migrate the field type in `options.proto`

---

dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR marks `(default_message)` option as `internal` and updates its docs.

Mark `(default_message)` as `internal`

---

dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR updates `field.name` notation to `field.path`. 
`(if_invalid)` option was removed. We have no plans to retain nested `ConstraintViolation`s. One error will mean one constraint violation, and it will use the original error message. The error message specified for `(validate)` is no longer needed.
Another aspect is that the options below expect field names to be passed to them, but may report invalid nested fields:
1. `(required_field)`.
3. `(goes_option)`.
If I write there `field.path`, it can be interpreted as "the option supports nested fields here". But they clearly do not support nested fields as input like `(compare_by)`, for example.

Talk about `field.path` in API of validation options

---

dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR restores binary compatibility with older versions. 
I can't migrate `spine-core` to the latest versions of `mc-java` and `validation`. And I can't remove usages of `if_invalid` without bumping the mentioned libs because the old versions were deleted from Maven.

Restore and deprecate `if_invalid` option

---

dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This updates the default error message for `(if_missing)`, so that it reads better for all field types.

Update the default error message for `(if_missing)`

---

buildSrc/src/main/kotlin/io/spine/dependency/build/Dokka.kt
buildSrc/src/main/kotlin/io/spine/dependency/build/Ksp.kt
buildSrc/src/main/kotlin/io/spine/dependency/lib/Auto.kt
buildSrc/src/main/kotlin/io/spine/dependency/lib/Kotlin.kt
buildSrc/src/main/kotlin/io/spine/dependency/lib/KotlinPoet.kt
buildSrc/src/main/kotlin/io/spine/dependency/lib/KotlinX.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/Base.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/Logging.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/ProtoData.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/Spine.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/TestLib.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/ToolBase.kt
buildSrc/src/main/kotlin/io/spine/dependency/local/Validation.kt
buildSrc/src/main/kotlin/io/spine/dependency/test/KotlinCompileTesting.kt
buildSrc/src/main/kotlin/io/spine/gradle/publish/CloudRepo.kt
buildSrc/src/main/kotlin/io/spine/gradle/report/pom/PomGenerator.kt
dependencies.md
pom.xml
src/main/java/io/spine/io/ResourceObject.java
version.gradle.kts

This PR fixes formatting in the error message when a `ResourceObject` is not found. `config` was also updated.

Fix diag message format in `ResourceObject`

---

dependencies.md
gradle/wrapper/gradle-wrapper.properties
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR actualizes specification of `(distinct)` option. 
We actually support `map` fields for this option in `validation`. And even [use](https://github.com/SpineEventEngine/ProtoData/blob/2600629bfc15434005c735775f878598a0a06989/api/src/main/proto/spine/protodata/source.proto#L63) it in ProtoData.
Discovered #855.

Update `(distinct)` docs

---

buildSrc/src/main/kotlin/io/spine/gradle/report/pom/PomGenerator.kt
buildSrc/src/main/kotlin/write-manifest.gradle.kts
dependencies.md
pom.xml
version.gradle.kts

This changeset restores the automatic generation of `pom.xml` file generation, which was recently broken during the migration to Gradle 8.13.
In particular, now the `generatePom` task is explicitly wired to `build` task. Previously, we have relied onto the fact that the "lazily evaluated" task action would execute at some point. However, apparently, it is not so anymore.
Another minor change is the migration from `tasks.creating ...` API call to `tasks.registering ...` It's just a newly encountered Gradle warning. It has nothing to do with the `pom.xml` generation.
By this PR, #855 is addressed.

Restore `pom.xml` generation

---

dependencies.md
pom.xml
src/main/kotlin/io/spine/protobuf/MessageExts.kt
src/test/kotlin/io/spine/protobuf/MessageExtsSpec.kt
version.gradle.kts

This PR adds the following alternatives to `builderFor(messageClass): Message.Builder`:
1. `Class<out Message>.newBuilder()` – to invoke upon Java classes.
2. `KClass<out Message>.newBuilder()` – to invoke upon Kotlin classes.
These extensions enhance readability when writing parametrized JUnit tests upon Protobuf messages that arrive as `KClass<Message>`:
```kotlin
assertThrows<ValidationException> {
message.newBuilder()
.set(field1, fieldValue1)
.build()
}
```
Also, I've updated docs wording from `Returns ...` to `Creates ...` because a new instance is actually returned, and new overloadings re-use the original function, so their docs should be consistent.

Add receiver-based overloadings for `builderFor(...)`

---

build.gradle.kts
dependencies.md
pom.xml
src/main/kotlin/io/spine/protobuf/ProtobufLiteral.kt
src/main/kotlin/io/spine/string/ProtobufLiteral.kt
src/main/proto/spine/options.proto
src/test/kotlin/io/spine/protobuf/ProtobufLiteralSpec.kt
version.gradle.kts

This PR does the following:
1. Clarifies docs to `(pattern)` option, mentioning which Regex dialect is expected by the option.
2. Implements `restoreProtobufEscapes()` function that allows to restore originally passed users' string literals, so that these literals could be rendered as literals in source files by `validation`.

Clarify `(pattern)` option and implement `restoreProtobufEscapes()` util

---

dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR adds more details to specification of the `(validate)` option.

Clarify docs to `(validate)` option

---

dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR updates docs to the `(range)` option and adds the `${field.value}` placeholder to the default error message.

Clarify `(range)` option and update its error message

---

dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR updates docs to `(min)` and `(max)` options.
The default error messages were also updated to include the field value.

Update docs to `(min)` and `(max)` options

---

dependencies.md
pom.xml
src/main/kotlin/io/spine/security/CallerProvider.kt
version.gradle.kts

This PR refactors `CallerProvider` extracting the common traversal code into a member extension function. Also, the object was made back `internal` because it's could not be reused for the `server.security` package as it was initially hoped.

Refactor `CallerProvider`

---

dependencies.md
pom.xml
src/main/proto/spine/options.proto
version.gradle.kts

This PR deprecates `(is_required)` and `(required_fields)` in favor of `(choice)` and `(require)` options, which are message-based now.
Please note that I retained `error_msg` field instead of `if_missing` to be in sync with the used convention. All companion fields ~ `(if_missing).error_msg` and message options ~ `(pattern).error_msg` already use this name.

Add `ChoiceOption` and `RequireOption`

---

base/src/main/proto/spine/options.proto
dependencies.md
pom.xml
version.gradle.kts

This PR re-brands `field combinations` from the `(require)` option to `field groups`.

Re-brand `field combinations` to `field groups`

---

base/src/main/java/io/spine/code/proto/AbstractOption.java
base/src/main/java/io/spine/protobuf/MessageFieldException.java
base/src/main/java/io/spine/type/ApiOption.java
base/src/main/kotlin/io/spine/type/BinaryExts.kt
base/src/main/kotlin/io/spine/type/ProtoTextExts.kt
buildSrc/src/main/kotlin/io/spine/dependency/lib/Protobuf.kt
dependencies.md
pom.xml
version.gradle.kts

This PR rolls back the version of the Protobuf runtime libraries as indicated in the issue title.
Still, we build the code using the latest version of Protobuf Gradle Plugin, which is `0.9.5`.
The rollback of the runtime version is needed for propagating the changes to the tool subprojects in the areas associated with working with options and corresponding generated `Extension` classes.

Rollback Protobuf `4.30.2` -> `3.25.7`

---

base/src/main/proto/spine/options.proto
dependencies.md
pom.xml
version.gradle.kts

This PR updates specs to `(min)`, `(max)` and `(range)` options to include support of referenced fields.

Update specs to numeric options to add field reference support

---

dependencies.md
format/src/main/kotlin/io/spine/format/Format.kt
pom.xml
version.gradle.kts

This PR adds missing documentation for the `Format` class.

Document properties and parameters of the `Format` class
